//! Periphery (real-on-disk-config, real-git, cross-module) tests for spec 88, criterion 1
//! (INTEGRATE-CONFLICT MERGES): a unit whose integration hits a merge conflict is re-parked
//! with the run branch merged INTO its worktree instead of being reset off it, and a conflict
//! confined to a registered `regenerate:` path resolves itself with no spawn.
//!
//! WHAT THE IMPLEMENTER'S OWN TESTS ALREADY COVER (not re-proven here). `src/worktree.rs`'s
//! own `mod tests` proves `Worktree::integrate`'s merge-direction flip directly:
//! `conflicting_paths`/`merge_in_progress` read real worktree state, a conflict leaves markers
//! in place with the unit branch untouched, and a crash-resumed re-entry is idempotent.
//! `src/conductor.rs`'s own `mod tests` drives `run()` end to end with a fake `AgentDriver`
//! for three shapes: a plain re-park that resolves and both units land with no attempt
//! charged, a conflict CONFINED ENTIRELY to a registered regenerable path resolving with no
//! spawn at all, and the `CONFLICT_RESOLVE_BOUND`-exhausted fallback charging a real attempt
//! with cause `"integrate-conflict"`. None of that is re-derived here.
//!
//! WHAT THIS FILE OWNS - four gaps those inside-out layers are structurally blind to, found
//! by re-reading the diff against `git merge-base HEAD rigger-run` rather than by inspection
//! alone (recorded as `sdet-u88c1-boundary-accounting` and, for GAP 4, added on round 1's own
//! diff as `sdet-u88c1r1-boundary-accounting` / `sdet-u88c1r1-gap4-added-and-verified`).
//!
//! GAP 1, `regenerate_config_round_trips_through_the_real_on_disk_loader_with_back_compat`. The
//! implementer's own tests build `cfg.workflow.regenerate` via Rust struct literals; none of
//! them ever parse a real `regenerate:` YAML block through `config::load` (the actual
//! `serde(Deserialize)` surface a hand-authored `.rigger/workflow.yml` exercises). This drives
//! the real on-disk loader for a multi-rule, multi-path block, for the back-compat case (an
//! omitted key - every workflow.yml committed before this criterion existed - must resolve to
//! an empty list, not an error), and for the REAL, currently-committed project
//! `.rigger/workflow.yml` itself, pinning its own `docs/audit/*` rule.
//!
//! GAP 2,
//! `a_mixed_source_and_regenerable_conflict_resolves_the_source_first_then_regenerates_for_real`.
//! The Design's own CONSTRAINTS WALK names a conflict spanning BOTH a source file and a
//! registered regenerable path ("the artifact is regenerated by the conductor after the
//! implementer resolves the source conflict, in that order"), and the production code has a
//! whole branch dedicated to it (`Worktree::accept_incoming`, `resolve_integrate_conflict`'s
//! `regenerable`/`source` partition with `regenerable` non-empty AND `source` non-empty). Every
//! one of the implementer's three new conductor tests conflicts on exactly one file, entirely
//! source or entirely regenerable - the MIXED branch has zero coverage anywhere in the diff.
//! This drives it across TWO real retries (round 1 review, adv-u88c1-mixed-conflict-regen-
//! skipped-on-multiretry: a single-retry drive left the multi-retry accumulation bug - the
//! `regenerable` path staged on retry 1 losing itself out of `resolve_integrate_conflict`'s
//! per-iteration partition by the time retry 2 finally clears the tree - entirely uncaught) and
//! proves the re-park's `blast_radius` names only the source path on every retry, the
//! regenerable path is placeholder-resolved just enough to unblock the commit, and the FINAL
//! landed content is the real regenerated output (not the incoming placeholder silently
//! standing in for it forever, which is exactly what a retry-1-then-done drive cannot observe).
//!
//! GAP 3, `a_post_merge_red_rollback_resets_the_units_own_branch_not_just_the_repo`. This
//! diff's OWN new code comment states the failure mode precisely: "its NEXT attempt would
//! fast-forward the repo from a branch still carrying the abandoned merge commit, silently
//! erasing whatever the repo held." The pre-existing spec-12-unit-5 `MergeBreakDriver` test
//! (unmodified by this diff, only cross-referenced from a doc comment) asserts the REPO's tree
//! and the recorded cause, but never once inspects the LOSING unit's OWN branch ref - so it
//! cannot see whether `unit_head_before_merge`'s reset actually fires. This drives the identical
//! clean-merge-then-red-postmerge-gate scenario and inspects the loser's own worktree at its
//! retry spawn: the branch there must be a single-parent commit (the abandoned two-parent merge
//! commit discarded) carrying exactly the loser's own prior work (not over-corrected back to
//! the shared base either).
//!
//! GAP 4 (round 1 review fix), `regenerate_conflicted_paths_runs_through_the_injected_gates_
//! port_not_a_raw_shell_out`. Round 1 fixed `run_regenerate_command` to call the injected
//! `gate::Runner` port (`Deps.gates`) instead of a raw, un-injected `std::process::Command`
//! shell-out (arch-u88c1-regenerate-bypasses-runner-port-and-build-budget) - but every existing
//! test that exercises regeneration, this file's own GAP 2 included, wires `Deps.gates` to the
//! REAL `ExecRunner`, which runs the registered command as a real shell either way and so cannot
//! tell the two implementations apart. This drives the confined-to-regenerable scenario with a
//! fake `Runner` that intercepts only the `"regenerate"` gate id and proves BOTH that the port is
//! actually called (with the exact gate id/command/dir) and that the port's own output - not a
//! parallel raw shell-out's - is what lands.
//!
//! GAP 5 (round 2 review fix), `regenerate_never_holds_integrate_mu_letting_an_unrelated_unit_
//! land_meanwhile`. The operator ruling op-u88c1-round-1-conflict-resolution-is-a-parked-spawn-
//! not-an-inline-loop (round 1 REJECT) required `integrate_mu` never span a conflict-resolution
//! implementer spawn; round 1's OWN fix (GAP 4 above) then routed `regenerate_conflicted_paths`
//! through the injected `gate::Runner` port and `Self::build_budget` - an UNBOUNDED wait when
//! every concurrency slot is taken (spec 65) - which round 2's review caught still running
//! WHILE `integrate_mu` was held (adv-u88c1r1-budget-fix-worsens-unfixed-lock-span): the exact
//! same class of defect the spawn fix had just closed, reopened one call site over. None of
//! this file's other tests can tell a held lock from a dropped one - GAP 4's own
//! `RecordingGateRunner` returns instantly. This drives the confined-to-regenerable scenario
//! (unit-a/unit-b) with a `Runner` that BLOCKS inside the `"regenerate"` gate id until released,
//! on a background thread, PLUS a third, entirely independent unit-c (gated to only attempt its
//! own merge once the block above is confirmed active - never racing ahead of it), and polls for
//! unit-c's own merge to land while that block is still in effect - which it only can if
//! `integrate_mu` was dropped around the call, never held across it. (A sibling of the
//! CONFLICT ITSELF cannot serve this proof: the loser of the integrate-lock race only ever
//! reaches the conflict AFTER the winner's own merge - post-merge gate included - already
//! finished and released the lock, so polling for the winner proves nothing either way.)
//!
//! GAP 6 (round 2 review fix), `a_crash_between_the_source_commit_and_regeneration_still_
//! regenerates_on_resume`. adv-u88c1r1-crash-resume-permanently-skips-regeneration (round 1
//! REJECT) was proven live by the round-1 adversary with a temporary probe test - explicitly
//! REVERTED afterward, never committed - so nothing on this branch actually holds the line. This
//! makes that proof permanent: a real two-call drive (not hand-seeded events) against the SAME
//! store and repo. Call 1's driver resolves the mixed conflict's SOURCE path for real (a genuine
//! git commit, landed on disk regardless of what the function returns) and then returns an
//! ordinary `Err` - a real process crash after the commit, before `regenerate_conflicted_paths`
//! ever runs, leaves exactly this on-disk state. Call 2 drives a FRESH `run()` against the same
//! store+repo with a driver that panics if the conflict-resolution role (a `~retry` implementer
//! id) is ever spawned again, proving `integrate_and_emit`'s `Merged` arm re-derives the still-
//! owed regeneration from the durable log marker (never re-entering conflict resolution) and the
//! regenerable path's FINAL content is the real regenerated output, not the crash-frozen
//! placeholder.
//!
//! GAP 7 (round 2 review fix), `a_non_content_merge_failure_surfaces_as_a_run_error_leaving_
//! branches_intact`. The round-2 fix for operator ruling point
//! (e) (`d-u88c1r2-worktree-merge-result-checked`, sdet-u88c1-worktree-merge-result-discarded)
//! makes `Worktree::integrate` surface a genuine `Err` for a non-content merge failure (a stray
//! untracked file `git merge --no-commit --no-ff` refuses to clobber) instead of silently
//! falling through - but its own proof (`src/worktree.rs`'s
//! `integrate_reports_a_non_content_merge_failure_instead_of_silently_landing_a_stale_branch`)
//! calls `Worktree::integrate` directly, never through the conductor. `integrate_and_emit`
//! (conductor.rs:7740) reads that `Err` through a bare `?` - a cross-module seam (Worktree ->
//! conductor -> the shared run branch and a batch-mate's own already-landed work) with zero
//! coverage anywhere in the diff. The ORIGINAL finding named exactly this as the fix's possible
//! new hazard: "hard-errors ... on the SHARED self.repo working directory ... a run-wedging
//! regression on shared state" - trading a silent-corruption bug for a shared-state-corrupting
//! one would be no fix at all. This drives it with two real batch-mates: `unit-b` lands a file
//! on the run branch for real (implementer -> gate -> review -> `wt.integrate`, no shortcuts),
//! `unit-a`'s own worktree - branched off the base BEFORE that landing - carries a stray FIFO at
//! that exact path so its own later `wt.integrate` hits the non-content failure. Proves the
//! whole `run()` call surfaces a genuine `Err`, `unit-b`'s already-landed content is untouched
//! by `unit-a`'s later failure, and `unit-a`'s own branch keeps its one real commit intact -
//! extending spec 88 criterion 1's "branch keeps every prior commit" guarantee to this
//! non-content failure, not just an ordinary content conflict.
//!
//! GAP 8 (round 3 fix's own untested safety claim),
//! `a_resumed_run_after_accept_incoming_fails_never_double_records_the_regenerate_pending_
//! marker`. Round 3 (`adv-u88c1r2-accept-incoming-precedes-durable-record-crash-window`,
//! upheld round 2 REJECT) reordered the mixed-conflict arm to durably record the still-owed
//! regeneration BEFORE `Worktree::accept_incoming`'s own git mutation, and the implementer's
//! own new `conductor.rs` unit test proves that ordering with a SINGLE `run()` call: a genuine
//! modify/delete conflict (`theirs` deleted the regenerable path) makes `accept_incoming` fail
//! for real, and the marker already landed despite it. That test's own reasoning names the
//! safety net for a REAL crash-then-resume as "`record_regenerate_pending`'s own per-path
//! dedup" - but per-path dedup is an IN-PROCESS `HashMap` (`conflict_regenerate_pending`) that
//! does not survive a real process restart at all; what actually protects a resumed `run()`
//! from double-recording is the LOG-KEYED replay guard `emit_keyed` rests on (spec 04,
//! criterion 4: `unit/conflict-regen#attempt~retry`, reseeded into `replayed_keys` from the
//! store at RunCtx construction) - and nothing anywhere in the diff calls `record_regenerate_
//! pending` twice against the SAME store to prove that guard actually fires here. This drives
//! a real two-call resume (mirrors GAP 6's technique) against the SAME still-conflicted
//! worktree - `accept_incoming` fails identically both times, since nothing between the calls
//! resolves the underlying modify/delete conflict - and asserts the durable marker is recorded
//! EXACTLY ONCE after each call, never twice, and that the resumed call skips straight to the
//! integrate door (`ResumePhase::Reviewed`) without ever re-spawning the implementer.

use rigger::conductor::{run, AgentDriver, AgentResult, Deps, Error, SpawnOpts, STREAM};
use rigger::config::{self, AgentDef, Config, RegenerateRule, Stage};
use rigger::eventstore::sqlite::Store;
use rigger::eventstore::{Direction, EventStore};
use rigger::ledger;
use serde_json::Value;
use std::path::Path;
use std::process::Command;
use std::sync::Mutex;

/// A throwaway git repo with one empty commit, so a run-branch anchor (`HEAD`) resolves.
/// Mirrors `src/conductor.rs::tests::init_repo` (private to that module) and every other
/// periphery suite's identical copy (e.g. `tests/worktree_liveness_fence_periphery.rs`).
fn init_repo() -> tempfile::TempDir {
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path().to_str().unwrap();
    for args in [
        &["init", "-q"][..],
        &["config", "user.email", "t@example.com"],
        &["config", "user.name", "t"],
        &["commit", "--allow-empty", "-q", "-m", "init"],
    ] {
        Command::new("git")
            .arg("-C")
            .arg(p)
            .args(args)
            .output()
            .unwrap();
    }
    dir
}

fn git_out(dir: &str, args: &[&str]) -> String {
    let out = Command::new("git")
        .arg("-C")
        .arg(dir)
        .args(args)
        .output()
        .unwrap_or_else(|e| panic!("git {args:?} in {dir}: {e}"));
    String::from_utf8_lossy(&out.stdout).trim().to_string()
}

fn git_commit_all(dir: &str, msg: &str) {
    for args in [&["add", "-A"][..], &["commit", "-q", "-m", msg]] {
        Command::new("git")
            .arg("-C")
            .arg(dir)
            .args(args)
            .output()
            .unwrap();
    }
}

/// `git add <only these paths>` then commit - deliberately NOT `-A`, mirroring a real
/// implementer that stages exactly the paths it was told to resolve (its own `blast_radius`).
/// `git commit` refuses outright while ANY path remains unmerged, even one this call never
/// touched - so this only succeeds when every OTHER conflicting path (the regenerable one) was
/// already resolved by someone else first, making a caller of this fn a genuine, load-bearing
/// proof that resolution happened, not a blanket `-A` that would silently paper over it.
fn git_commit_paths(dir: &str, paths: &[&str], msg: &str) {
    let mut add = vec!["add", "--"];
    add.extend_from_slice(paths);
    for args in [add, vec!["commit", "-q", "-m", msg]] {
        let out = Command::new("git")
            .arg("-C")
            .arg(dir)
            .args(&args)
            .output()
            .unwrap_or_else(|e| panic!("git {args:?} in {dir}: {e}"));
        assert!(
            out.status.success(),
            "git {args:?} in {dir} failed (a leftover unresolved conflict would show up here): \
             {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }
}

fn agent(id: &str) -> AgentDef {
    AgentDef {
        id: id.to_string(),
        ..Default::default()
    }
}

fn gate_def(run: &str) -> config::Gate {
    config::Gate {
        run: run.to_string(),
        kind: "core".to_string(),
        inputs: Vec::new(),
    }
}

fn review_panel() -> config::ReviewPanel {
    config::ReviewPanel {
        lenses: vec!["lens".into()],
        adjudicator: "judge".into(),
        ..Default::default()
    }
}

/// The shared review-tier response every fake `AgentDriver` in this file returns for a
/// non-implementer spawn: the adjudicator approves outright, any other reviewer role's own
/// output is unread by the tests below (only its APPROVE verdict matters). One function, not a
/// third copy of the same two-armed match hand-duplicated across driver structs.
fn review_or_adjudicate(opts: &SpawnOpts) -> AgentResult {
    if opts.id.contains("/adjudicator#") {
        return AgentResult {
            output: r#"{"verdict":"approve"}"#.into(),
            resolved_model: String::new(),
        };
    }
    AgentResult {
        output: "reviewed the diff".into(),
        resolved_model: String::new(),
    }
}

fn mk_stage(name: &str, gate: &str) -> Stage {
    Stage {
        name: name.into(),
        agent: "worker".into(),
        gates: vec![gate.into()],
        on_pass: "merge".into(),
        needs: vec![],
        review: review_panel(),
        ..Default::default()
    }
}

// ============================================================================================
// Gap 1: the `regenerate:` YAML surface never round-trips through the real on-disk loader
// anywhere in the diff.
// ============================================================================================

/// Write a minimal but real `.rigger/agents/worker.md` + `.rigger/workflow.yml` at `root`, so
/// `config::load` reaches all the way through agent parsing and `Config::validate` - the real
/// on-disk boundary, not a struct literal built in memory. Mirrors
/// `tests/build_budget_slots_periphery.rs::write_workflow`'s identical technique for
/// `build.max_concurrent` (spec 65), now for `regenerate:` (spec 88, criterion 1).
/// `regenerate_block` is appended verbatim: `""` omits the section entirely (the back-compat
/// case).
fn write_workflow(root: &Path, regenerate_block: &str) {
    let rigger = root.join(".rigger");
    std::fs::create_dir_all(rigger.join("agents")).expect("create .rigger/agents");
    std::fs::write(
        rigger.join("agents").join("worker.md"),
        "---\nid: worker\nmodel: sonnet\ntools: [Read, Edit]\nisolation: none\n---\nDo the unit.\n",
    )
    .expect("write worker.md");
    let workflow = format!(
        "name: regeneratetest\n\
         defaults:\n  grounder: nop\n  budget: 60\n\
         stages:\n  a:\n    agent: worker\n    on_pass: none\n\
         {regenerate_block}"
    );
    std::fs::write(rigger.join("workflow.yml"), workflow).expect("write workflow.yml");
}

#[test]
fn regenerate_config_round_trips_through_the_real_on_disk_loader_with_back_compat() {
    // (a) a real regenerate: block, TWO rules, the first with TWO paths - proves the YAML
    // shape (a list of {paths: [...], run: ...} maps) round-trips field-for-field through
    // the real serde(Deserialize) surface, not just that SOME shape parses.
    let configured = tempfile::tempdir().expect("create temp project");
    write_workflow(
        configured.path(),
        "regenerate:\n\
         - paths: [\"docs/audit/*\", \"docs/other/*\"]\n\
         \u{20}\u{20}run: \"echo one\"\n\
         - paths: [\"gen/*.json\"]\n\
         \u{20}\u{20}run: \"echo two\"\n",
    );
    let cfg = config::load(configured.path().to_str().unwrap()).expect("load a valid workflow.yml");
    assert_eq!(
        cfg.workflow.regenerate.len(),
        2,
        "both rules must round-trip: {:?}",
        cfg.workflow.regenerate
    );
    assert_eq!(
        cfg.workflow.regenerate[0].paths,
        vec!["docs/audit/*".to_string(), "docs/other/*".to_string()]
    );
    assert_eq!(cfg.workflow.regenerate[0].run, "echo one");
    assert_eq!(
        cfg.workflow.regenerate[1].paths,
        vec!["gen/*.json".to_string()]
    );
    assert_eq!(cfg.workflow.regenerate[1].run, "echo two");

    // (b) the back-compat case: an OMITTED regenerate: key - every workflow.yml committed
    // before this criterion existed - must still load cleanly through the real loader and
    // resolve to an EMPTY list (every conflict re-parks the implementer exactly as it would
    // otherwise, per Workflow::regenerate's own doc comment), never an error and never a
    // silently-defaulted rule.
    let legacy = tempfile::tempdir().expect("create temp project");
    write_workflow(legacy.path(), "");
    let cfg = config::load(legacy.path().to_str().unwrap())
        .expect("a workflow.yml with no regenerate: section must still load");
    assert!(
        cfg.workflow.regenerate.is_empty(),
        "an omitted regenerate: section must resolve to an empty list through the real loader; \
         got {:?}",
        cfg.workflow.regenerate
    );

    // (c) the REAL, currently-committed project workflow.yml - not a synthetic fixture. It
    // must load through the exact same `config::load` path `main.rs` uses in production, and
    // its own registered rule (this diff's own worked example) must be exactly what the
    // committed file states: `docs/audit/*` regenerated via the simplification_audit test.
    let project_root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let real_cfg = config::load(project_root.to_str().unwrap())
        .expect("the project's own .rigger/workflow.yml must load through the real loader");
    assert!(
        real_cfg
            .workflow
            .regenerate
            .iter()
            .any(|r| r.paths == vec!["docs/audit/*".to_string()]
                && r.run.contains("simplification_audit")),
        "the real committed workflow.yml must register docs/audit/* as regenerable via the \
         simplification_audit regeneration command; got: {:?}",
        real_cfg.workflow.regenerate
    );
}

// ============================================================================================
// Gap 2: a conflict spanning BOTH a source path and a registered regenerable path (the
// Design's own CONSTRAINTS WALK scenario) has zero coverage anywhere in the diff.
// ============================================================================================

/// Drives the spec 88, criterion 1 MIXED-conflict fixture: `unit-a` and `unit-b` are two
/// batch-mates with no dependency, both editing the SAME LINE of BOTH `c.rs` (a plain source
/// file) and `docs/audit/report.md` (registered regenerable) off the same base - so the loser's
/// merge conflicts in both files at once. The barrier makes both worktrees branch from the same
/// base before either writes. The loser's own implementer is re-parked under a `~retry` id to
/// resolve ONLY the source conflict - across TWO real retries, not one: `~retry1` deliberately
/// leaves `c.rs` conflicted and commits nothing (forcing `resolve_integrate_conflict` around for
/// a SECOND pass, whose OWN `regenerable` partition of the by-then-shrunk `conflicting_paths()`
/// comes up empty - the exact shape `adv-u88c1-mixed-conflict-regen-skipped-on-multiretry`
/// found unaccumulated), then `~retry2` resolves it for real by overwriting `c.rs` with fixed
/// content and committing on the SAME branch. `docs/audit/report.md` is never touched by the
/// driver at any retry - left exactly as the conductor's own placeholder resolution (staged once,
/// on retry 1's iteration) left it - so the final content proves whether real regeneration ran
/// afterward, and specifically whether it still ran when the path that needed it was staged on
/// an EARLIER retry than the one that finally cleared the tree.
struct MixedConflictDriver {
    repo: String,
    calls: Mutex<Vec<String>>,
    /// `blast_radius` the conductor gave the retry spawn - captured so the test can assert it
    /// names only the source path, never the regenerable one.
    retry_blast_radius: Mutex<Option<Vec<String>>>,
}

impl AgentDriver for MixedConflictDriver {
    fn spawn(
        &self,
        _a: &AgentDef,
        _prompt: &str,
        opts: &SpawnOpts,
        _emit: &dyn Fn(&str, Value) -> Result<(), Error>,
    ) -> Result<AgentResult, Error> {
        self.calls.lock().unwrap().push(opts.id.clone());
        let unit = opts.id.split('/').next().unwrap_or_default();
        if opts.id.contains("/implementer#") {
            if opts.id.contains("~retry1") {
                assert!(
                    !opts.dir.is_empty(),
                    "a conflict re-park must still run in the unit's own worktree"
                );
                *self.retry_blast_radius.lock().unwrap() = Some(opts.blast_radius.clone());
                // Deliberately does NOT resolve the source conflict and commits nothing -
                // `c.rs` is left with its conflict markers exactly as `resolve_integrate_
                // conflict` found it. `docs/audit/report.md`, though, WAS already
                // placeholder-staged (via `accept_incoming`) before this spawn ran, so it no
                // longer shows up in `conflicting_paths()` either way. This forces the loop
                // around for a genuine SECOND retry, whose own `regenerable` partition of the
                // (by then audit-report-free) `conflicting` list comes up empty - the exact
                // shape that left the placeholder permanently on the run branch before the
                // fix: regeneration must still fire on retry 2's clean tree, from the
                // conductor's OWN accumulated bookkeeping, not from this iteration's local
                // partition.
                return Ok(AgentResult::default());
            }
            if opts.id.contains("~retry2") {
                assert!(
                    !opts.dir.is_empty(),
                    "a conflict re-park must still run in the unit's own worktree"
                );
                *self.retry_blast_radius.lock().unwrap() = Some(opts.blast_radius.clone());
                // NOW resolve the source conflict for real. `docs/audit/report.md` is still
                // left exactly as the conductor's own accept_incoming placeholder left it on
                // retry 1 - untouched here too - so the final landed content distinguishes
                // "the conductor really regenerated it afterward" from "the placeholder
                // silently stood in forever".
                std::fs::write(Path::new(&opts.dir).join("c.rs"), "RESOLVED_C\n").unwrap();
                // Stage and commit ONLY c.rs, the source path this spawn was told about - NOT
                // a blanket `-A`. `git commit` refuses outright while ANY path is still
                // unmerged, so this line only succeeds if `docs/audit/report.md` (which this
                // spawn never touches at all) was ALREADY resolved by the conductor's own
                // accept_incoming placeholder before this spawn ran - making this call itself
                // load-bearing proof that placeholder resolution happened, not merely a
                // downstream assertion that could pass by accident.
                git_commit_paths(&opts.dir, &["c.rs"], "resolve source conflict");
                return Ok(AgentResult::default());
            }
            if !opts.dir.is_empty() {
                for _ in 0..400 {
                    let n = Command::new("git")
                        .arg("-C")
                        .arg(&self.repo)
                        .args(["branch", "--list", "rigger/u/*"])
                        .output()
                        .map(|o| String::from_utf8_lossy(&o.stdout).lines().count())
                        .unwrap_or(0);
                    if n >= 2 {
                        break;
                    }
                    std::thread::sleep(std::time::Duration::from_millis(25));
                }
                let (c, audit) = if unit == "unit-a" {
                    ("A_C\n", "A_AUDIT\n")
                } else {
                    ("B_C\n", "B_AUDIT\n")
                };
                std::fs::write(Path::new(&opts.dir).join("c.rs"), c).unwrap();
                std::fs::create_dir_all(Path::new(&opts.dir).join("docs/audit")).unwrap();
                std::fs::write(Path::new(&opts.dir).join("docs/audit/report.md"), audit).unwrap();
            }
            return Ok(AgentResult::default());
        }
        Ok(review_or_adjudicate(opts))
    }
}

#[test]
fn a_mixed_source_and_regenerable_conflict_resolves_the_source_first_then_regenerates_for_real() {
    let repo = init_repo();
    let repo_path = repo.path().to_str().unwrap().to_string();
    std::fs::create_dir_all(Path::new(&repo_path).join("docs/audit")).unwrap();
    std::fs::write(Path::new(&repo_path).join("c.rs"), "BASE_C\n").unwrap();
    std::fs::write(
        Path::new(&repo_path).join("docs/audit/report.md"),
        "BASE_AUDIT\n",
    )
    .unwrap();
    git_commit_all(&repo_path, "base c.rs + docs/audit/report.md");

    let store = Store::open(":memory:").unwrap();
    let driver = MixedConflictDriver {
        repo: repo_path.clone(),
        calls: Mutex::new(Vec::new()),
        retry_blast_radius: Mutex::new(None),
    };

    let mut cfg = Config::default();
    cfg.workflow.defaults.max_retries = 3;
    cfg.workflow.regenerate = vec![RegenerateRule {
        paths: vec!["docs/audit/*".into()],
        run: "printf 'REGENERATED\\n' > docs/audit/report.md".into(),
    }];
    cfg.agents.insert("worker".into(), agent("worker"));
    cfg.agents.insert("lens".into(), agent("lens"));
    cfg.agents.insert("judge".into(), agent("judge"));
    cfg.workflow.gates.insert("g".into(), gate_def("exit 0"));
    cfg.workflow
        .stages
        .insert("unit-a".into(), mk_stage("unit-a", "g"));
    cfg.workflow
        .stages
        .insert("unit-b".into(), mk_stage("unit-b", "g"));

    let deps = Deps {
        store: &store,
        driver: &driver,
        gates: &rigger::gate::ExecRunner,
        repo: repo_path.clone(),
        grounder: None,
        graph: None,
        criteria: Vec::new(),
    };
    let rs = run(&cfg, &deps).unwrap();

    assert_eq!(rs.units["unit-a"].status, ledger::Status::Integrated);
    assert_eq!(
        rs.units["unit-b"].status,
        ledger::Status::Integrated,
        "the mixed conflict must still land, not dead-end"
    );
    assert_eq!(rs.units["unit-a"].attempts, 0);
    assert_eq!(
        rs.units["unit-b"].attempts, 0,
        "no remediation attempt is charged for a conflict, mixed or not"
    );

    // TWO real retry re-parks (round 1 review fix for adv-u88c1-mixed-conflict-regen-skipped-
    // on-multiretry): retry 1 deliberately leaves the source conflict unresolved, forcing
    // `resolve_integrate_conflict` around for a genuine second pass before it converges. Both
    // re-parks' blast_radius names ONLY the source path - the regenerable path the conductor
    // resolves itself must never reach the implementer, on either retry.
    let calls = driver.calls.lock().unwrap();
    assert!(
        calls.iter().any(|id| id.contains("/implementer#0~retry1")),
        "unit-b's implementer must be re-parked under a ~retry1 id; got {calls:?}"
    );
    assert!(
        calls.iter().any(|id| id.contains("/implementer#0~retry2")),
        "the mixed conflict must genuinely need a SECOND re-park (retry 1 deliberately leaves \
         it unresolved) to exercise the multi-retry regenerable-path bookkeeping; got {calls:?}"
    );
    let blast = driver.retry_blast_radius.lock().unwrap().clone();
    assert_eq!(
        blast,
        Some(vec!["c.rs".to_string()]),
        "the re-park's blast_radius must name only the source path, never the regenerable one \
         (checked against the LAST re-park, retry 2)"
    );

    // The FINAL landed content: c.rs carries the implementer's real resolution (from retry 2),
    // and docs/audit/report.md carries the conductor's REAL regenerated output - not the
    // accept_incoming placeholder (unit-a's "A_AUDIT\n") silently standing in forever. This is
    // the assertion the single-retry drive could never exercise: `docs/audit/report.md` was
    // placeholder-staged back on retry 1's iteration, two retries before the tree actually
    // clears on retry 2 - proving the conductor's accumulated bookkeeping (not retry 2's own,
    // by-then-empty `regenerable` partition) is what drives the real regeneration.
    let final_c = std::fs::read_to_string(Path::new(&repo_path).join("c.rs")).unwrap();
    assert_eq!(final_c, "RESOLVED_C\n");
    let final_audit =
        std::fs::read_to_string(Path::new(&repo_path).join("docs/audit/report.md")).unwrap();
    assert_eq!(
        final_audit, "REGENERATED\n",
        "the regenerable path must carry the conductor's OWN regenerated output, not the \
         placeholder incoming content the merge left it with"
    );

    // The conductor's own follow-up regeneration commit is a real, separately-attributable
    // commit (the design's "in that order"), not squashed into the implementer's resolution
    // commit. Read off the REPO's own current branch (not the unit's `rigger/u/*` ref, which
    // an integrated unit's branch/worktree may already have been reclaimed by the time this
    // assertion runs) - it carries the full landed history regardless.
    let log = git_out(&repo_path, &["log", "--format=%s"]);
    assert!(
        log.contains("regenerate conflicting artifacts for"),
        "the conductor's own regeneration commit must land as a distinct commit after the \
         implementer's resolution commit; log:\n{log}"
    );
    assert!(
        log.contains("resolve source conflict"),
        "the implementer's own resolution commit must land as its own distinct commit too; \
         log:\n{log}"
    );
    drop(repo);
}

// ============================================================================================
// Gap 3: the NEW `unit_head_before_merge` branch reset on a clean-merge-then-red-postmerge-gate
// - this diff's own doc comment names the exact failure mode a missing reset produces, and the
// pre-existing spec-12-unit-5 test never inspects the loser's own branch ref.
// ============================================================================================

const MB_BASE: &str = "unrelated line one\nunrelated line two\n";

/// Drives the identical clean-merge-then-red-postmerge-gate scenario the pre-existing
/// `MergeBreakDriver` (spec 12, unit 5) proves lands correctly on the REPO - `unit-a` prepends a
/// mark, `unit-b` appends one off the same base; both gate green alone, the merge auto-succeeds
/// (non-overlapping regions), but the merged tree carries two marks and the post-merge gate
/// rejects it. WHICH of the two loses the integrate-lock race (and so hits the post-merge-red
/// block) is a genuine race MergeBreakDriver itself never pins either - so, unlike that driver,
/// BOTH units here behave identically and symmetrically per attempt: attempt 0 reproduces the
/// break (prepend for a, append for b - so the loser's merge auto-succeeds without a raw
/// conflict), any later attempt - BEFORE writing anything - snapshots the worktree's CURRENT
/// branch state (the thing this test actually pins: a single-parent commit carrying the loser's
/// own prior work, or the abandoned two-parent merge commit the reset should have discarded)
/// and then writes NEUTRAL content (reverts its own side to unchanged base) so the retry's merge
/// carries only the winner's one mark and gates green.
struct BranchResetDriver {
    repo: String,
    /// One entry per unit whose implementer ran at `attempt > 0`: `(parent count, m.rs content)`
    /// of its worktree HEAD, captured before this driver wrote anything that attempt - i.e. the
    /// state the conductor's post-merge-red rollback left it in. Whichever of unit-a/unit-b
    /// loses the race gets exactly one entry here; the winner (never blocked, never retried)
    /// gets none.
    retry_snapshots: Mutex<std::collections::HashMap<String, (usize, String)>>,
}

impl AgentDriver for BranchResetDriver {
    fn spawn(
        &self,
        _a: &AgentDef,
        _prompt: &str,
        opts: &SpawnOpts,
        _emit: &dyn Fn(&str, Value) -> Result<(), Error>,
    ) -> Result<AgentResult, Error> {
        let unit = opts.id.split('/').next().unwrap_or_default().to_string();
        if opts.id.contains("/implementer#") {
            if !opts.dir.is_empty() {
                if opts.attempt == 0 {
                    for _ in 0..400 {
                        let n = Command::new("git")
                            .arg("-C")
                            .arg(&self.repo)
                            .args(["branch", "--list", "rigger/u/*"])
                            .output()
                            .map(|o| String::from_utf8_lossy(&o.stdout).lines().count())
                            .unwrap_or(0);
                        if n >= 2 {
                            break;
                        }
                        std::thread::sleep(std::time::Duration::from_millis(25));
                    }
                    // Reproduces the break: each unit adds its OWN mark in a DIFFERENT,
                    // non-overlapping region (prepend for a, append for b), same as
                    // MergeBreakDriver - whichever one integrates second merges cleanly into a
                    // tree that already carries the other's mark, producing two.
                    let content = if unit == "unit-a" {
                        format!("MARK\n{MB_BASE}")
                    } else {
                        format!("{MB_BASE}MARK\n")
                    };
                    std::fs::write(Path::new(&opts.dir).join("m.rs"), content).unwrap();
                } else {
                    // The retry: snapshot BEFORE writing anything - this is the state the
                    // conductor's post-merge-red rollback left the worktree in.
                    let head = git_out(&opts.dir, &["rev-parse", "HEAD"]);
                    let parents = git_out(&opts.dir, &["log", "-1", "--format=%P", &head]);
                    let parent_count = if parents.trim().is_empty() {
                        0
                    } else {
                        parents.split_whitespace().count()
                    };
                    let content =
                        std::fs::read_to_string(Path::new(&opts.dir).join("m.rs")).unwrap();
                    self.retry_snapshots
                        .lock()
                        .unwrap()
                        .insert(unit, (parent_count, content));
                    // The real fix: contribute NOTHING further to the shared region - this
                    // unit's own portion reverts to unchanged base, so the merged tree carries
                    // only the other unit's one mark and the post-merge gate goes green.
                    std::fs::write(Path::new(&opts.dir).join("m.rs"), MB_BASE).unwrap();
                }
            }
            return Ok(AgentResult::default());
        }
        Ok(review_or_adjudicate(opts))
    }
}

#[test]
fn a_post_merge_red_rollback_resets_the_units_own_branch_not_just_the_repo() {
    let repo = init_repo();
    let repo_path = repo.path().to_str().unwrap().to_string();
    std::fs::write(Path::new(&repo_path).join("m.rs"), MB_BASE).unwrap();
    git_commit_all(&repo_path, "base m.rs");

    let store = Store::open(":memory:").unwrap();
    let driver = BranchResetDriver {
        repo: repo_path.clone(),
        retry_snapshots: Mutex::new(std::collections::HashMap::new()),
    };

    let mut cfg = Config::default();
    // whichever unit loses the integrate-lock race must survive its FIRST block and get a
    // real second attempt: at least 2.
    cfg.workflow.defaults.max_retries = 2;
    cfg.agents.insert("worker".into(), agent("worker"));
    cfg.agents.insert("lens".into(), agent("lens"));
    cfg.agents.insert("judge".into(), agent("judge"));
    cfg.workflow.gates.insert(
        "g".into(),
        gate_def(
            "c=$(grep -c MARK m.rs 2>/dev/null); c=${c:-0}; \
             if [ \"$c\" -le 1 ]; then exit 0; else \
             echo 'gate g failed: merge introduced duplicate MARK'; exit 1; fi",
        ),
    );
    cfg.workflow
        .stages
        .insert("unit-a".into(), mk_stage("unit-a", "g"));
    cfg.workflow
        .stages
        .insert("unit-b".into(), mk_stage("unit-b", "g"));

    let deps = Deps {
        store: &store,
        driver: &driver,
        gates: &rigger::gate::ExecRunner,
        repo: repo_path.clone(),
        grounder: None,
        graph: None,
        criteria: Vec::new(),
    };
    let rs = run(&cfg, &deps).unwrap();

    // Both units integrate: the winner cleanly, the loser (whichever one lost the
    // integrate-lock race - a genuine race MergeBreakDriver itself never pins either) after
    // its rollback-and-retry recovers.
    assert_eq!(rs.units["unit-a"].status, ledger::Status::Integrated);
    assert_eq!(
        rs.units["unit-b"].status,
        ledger::Status::Integrated,
        "both units must land, or this test proves nothing about the retry state"
    );

    // Exactly one of the two took a retry (the loser); the winner never blocked.
    let snapshots = driver.retry_snapshots.lock().unwrap();
    assert_eq!(
        snapshots.len(),
        1,
        "exactly one unit (the loser of the integrate-lock race) must have retried; got {:?}",
        snapshots.keys().collect::<Vec<_>>()
    );
    let (loser, (parent_count, content)) = snapshots.iter().next().unwrap();
    let own_mark = if loser == "unit-a" {
        format!("MARK\n{MB_BASE}")
    } else {
        format!("{MB_BASE}MARK\n")
    };

    // The actual claim: at the retry, the loser's worktree HEAD was a SINGLE-parent commit
    // (the abandoned two-parent auto-merge commit was discarded by the branch reset, not just
    // the repo) carrying EXACTLY the loser's own prior work - not the base content either
    // (which would mean the reset over-corrected and threw away its real, reviewed work too).
    assert_eq!(
        *parent_count, 1,
        "{loser}'s own branch must be reset to its single-parent pre-merge commit, not left \
         carrying the abandoned two-parent merge commit the post-merge-red rollback discarded \
         on the repo side"
    );
    assert_eq!(
        *content, own_mark,
        "the reset must land on EXACTLY {loser}'s own prior work (its one-mark commit), \
         neither the abandoned merge commit's two-mark content nor an over-corrected reset all \
         the way back to the shared base"
    );

    // The merged tree carries exactly one mark (the winner's); the broken two-mark tree from
    // the loser's first attempt never landed.
    let merged = std::fs::read_to_string(Path::new(&repo_path).join("m.rs")).unwrap();
    assert_eq!(
        merged.matches("MARK").count(),
        1,
        "the run branch holds only the winner's one mark: {merged}"
    );

    // The block that triggered the rollback is stamped "integrate-conflict" (spec 69's cause
    // wire), same as the pre-existing MergeBreakDriver test - reused here as a sanity check,
    // not re-derived.
    let events = store.read_stream(STREAM, 0, Direction::Forward).unwrap();
    let cause = events
        .iter()
        .find(|e| {
            e.type_ == ledger::TYPE_UNIT_FAILED
                && String::from_utf8_lossy(&e.data).contains(&format!("\"id\":\"{loser}\""))
        })
        .map(|e| serde_json::from_slice::<Value>(&e.data).unwrap()["cause"].clone());
    assert_eq!(cause, Some(Value::String("integrate-conflict".into())));
    drop(repo);
}

// ============================================================================================
// Gap 4: `run_regenerate_command`'s NEW cross-module call into the injected `gate::Runner`
// port (round 1 review fix for arch-u88c1-regenerate-bypasses-runner-port-and-build-budget) has
// zero test anywhere that can tell a real port-routed call apart from a raw, un-injected
// `std::process::Command` shell-out producing the same visible result: every existing test that
// exercises regeneration - the implementer's own three conductor.rs unit tests AND this file's
// GAP 2 - wires `Deps.gates` to the REAL `rigger::gate::ExecRunner`, which actually runs the
// registered shell command either way. Reverting `run_regenerate_command` back to a raw
// `std::process::Command::new("sh")` call (the exact regression the fix's own doc comment names)
// would still make every one of those tests pass unchanged, because they only ever check the
// resulting file content, never which side of the port boundary produced it.
// ============================================================================================

/// A [`rigger::gate::Runner`] fake that ONLY intercepts the `"regenerate"` gate id (recording
/// its call - gate id, gate run command, dir - and writing its OWN sentinel content instead of
/// actually running `g.run` as a shell command); every OTHER gate id (a unit's ordinary `"g"`
/// gate, the post-merge re-gate) delegates straight to the REAL [`rigger::gate::ExecRunner`], so
/// this fake changes nothing about how the surrounding conflict/merge/gate machinery behaves -
/// it observes exactly one seam. The regenerate rule's `run` string below is deliberately a
/// command that would write DIFFERENT content if a raw shell ever executed it for real, so the
/// two paths can never coincidentally agree on the final file content: only one of them can have
/// produced it.
struct RecordingGateRunner {
    calls: Mutex<Vec<(String, String, String)>>,
}

impl rigger::gate::Runner for RecordingGateRunner {
    fn run(
        &self,
        g: &rigger::gate::Gate,
        dir: &str,
        target_dir: &str,
        build_cache_dir: &str,
        build_cache_guard: &str,
        store_fence: &str,
        build_env: &rigger::gate::BuildEnv,
        budget: &rigger::budget::BuildBudget,
    ) -> rigger::gate::GateResult {
        if g.id != "regenerate" {
            return rigger::gate::ExecRunner.run(
                g,
                dir,
                target_dir,
                build_cache_dir,
                build_cache_guard,
                store_fence,
                build_env,
                budget,
            );
        }
        self.calls
            .lock()
            .unwrap()
            .push((g.id.clone(), g.run.clone(), dir.to_string()));
        std::fs::write(Path::new(dir).join("c.rs"), "FAKE_REGEN_VIA_PORT\n").unwrap();
        rigger::gate::GateResult {
            pass: true,
            evidence: "fake runner: regenerated via the injected port, never a raw shell".into(),
        }
    }
}

/// Same two-batch-mates-same-line-off-the-same-base shape as the implementer's own
/// `conflict_fixture` (conductor.rs) and this file's other drivers: `c.rs` is registered
/// regenerable, so the loser's conflict resolves with NO implementer spawn at all - this test's
/// whole point is the conductor's OWN regeneration call, not anything an implementer does.
struct GatesPortConflictDriver {
    repo: String,
    calls: Mutex<Vec<String>>,
}

impl AgentDriver for GatesPortConflictDriver {
    fn spawn(
        &self,
        _a: &AgentDef,
        _prompt: &str,
        opts: &SpawnOpts,
        _emit: &dyn Fn(&str, Value) -> Result<(), Error>,
    ) -> Result<AgentResult, Error> {
        self.calls.lock().unwrap().push(opts.id.clone());
        let unit = opts.id.split('/').next().unwrap_or_default();
        if opts.id.contains("/implementer#") {
            if !opts.dir.is_empty() {
                // Barrier: wait until BOTH units' worktrees exist before either writes, so both
                // branch off the identical base commit (mirrors MixedConflictDriver above).
                for _ in 0..400 {
                    let n = Command::new("git")
                        .arg("-C")
                        .arg(&self.repo)
                        .args(["branch", "--list", "rigger/u/*"])
                        .output()
                        .map(|o| String::from_utf8_lossy(&o.stdout).lines().count())
                        .unwrap_or(0);
                    if n >= 2 {
                        break;
                    }
                    std::thread::sleep(std::time::Duration::from_millis(25));
                }
                let content = if unit == "unit-a" {
                    "A_LINE\n"
                } else {
                    "B_LINE\n"
                };
                std::fs::write(Path::new(&opts.dir).join("c.rs"), content).unwrap();
            }
            return Ok(AgentResult::default());
        }
        Ok(review_or_adjudicate(opts))
    }
}

#[test]
fn regenerate_conflicted_paths_runs_through_the_injected_gates_port_not_a_raw_shell_out() {
    let repo = init_repo();
    let repo_path = repo.path().to_str().unwrap().to_string();
    std::fs::write(Path::new(&repo_path).join("c.rs"), "BASE\n").unwrap();
    git_commit_all(&repo_path, "base c.rs");

    let store = Store::open(":memory:").unwrap();
    let driver = GatesPortConflictDriver {
        repo: repo_path.clone(),
        calls: Mutex::new(Vec::new()),
    };
    let runner = RecordingGateRunner {
        calls: Mutex::new(Vec::new()),
    };

    let mut cfg = Config::default();
    cfg.workflow.defaults.max_retries = 3;
    cfg.workflow.regenerate = vec![RegenerateRule {
        paths: vec!["c.rs".into()],
        run: "printf 'REAL_SHELL_WOULD_WRITE_THIS\\n' > c.rs".into(),
    }];
    cfg.agents.insert("worker".into(), agent("worker"));
    cfg.agents.insert("lens".into(), agent("lens"));
    cfg.agents.insert("judge".into(), agent("judge"));
    cfg.workflow.gates.insert("g".into(), gate_def("exit 0"));
    cfg.workflow
        .stages
        .insert("unit-a".into(), mk_stage("unit-a", "g"));
    cfg.workflow
        .stages
        .insert("unit-b".into(), mk_stage("unit-b", "g"));

    let deps = Deps {
        store: &store,
        driver: &driver,
        gates: &runner,
        repo: repo_path.clone(),
        grounder: None,
        graph: None,
        criteria: Vec::new(),
    };
    let rs = run(&cfg, &deps).unwrap();

    assert_eq!(rs.units["unit-a"].status, ledger::Status::Integrated);
    assert_eq!(
        rs.units["unit-b"].status,
        ledger::Status::Integrated,
        "a conflict confined entirely to a registered regenerable path must still land"
    );
    assert_eq!(rs.units["unit-a"].attempts, 0);
    assert_eq!(rs.units["unit-b"].attempts, 0);

    let calls = driver.calls.lock().unwrap();
    assert!(
        !calls.iter().any(|id| id.contains("~retry")),
        "a conflict confined to a registered regenerable path resolves with NO spawn; got {calls:?}"
    );

    // THE decisive proof of DI routing: the injected port was actually invoked, carrying the
    // EXACT gate id and command `run_regenerate_command` documents constructing, in the unit's
    // own worktree dir - never the shared repo dir.
    let runs = runner.calls.lock().unwrap();
    assert_eq!(
        runs.len(),
        1,
        "regenerate_conflicted_paths must call the injected gate::Runner port exactly once for \
         the one distinct registered command; got {runs:?}"
    );
    let (id, run_cmd, dir) = &runs[0];
    assert_eq!(
        id, "regenerate",
        "run_regenerate_command's own Gate literal must carry id \"regenerate\""
    );
    assert_eq!(
        run_cmd, "printf 'REAL_SHELL_WOULD_WRITE_THIS\\n' > c.rs",
        "the injected port must receive the EXACT command the registered RegenerateRule names"
    );
    assert_ne!(
        dir, &repo_path,
        "the port must be called with the LOSING unit's own worktree dir, never the shared repo \
         (the worktree itself may already be reclaimed by the time this assertion runs, since \
         both units have finished integrating - matching GAP 2/3's own convention of reading \
         final state off the repo, never a per-unit worktree, after `run()` returns)"
    );
    assert!(
        dir.contains("unit-a") || dir.contains("unit-b"),
        "the regenerable-confined conflict belongs to whichever unit loses the integrate-lock \
         race (a genuine race, never pinned - see GAP 3's identical caveat); got {dir}"
    );

    // The final landed content is the FAKE runner's own sentinel - never the string a raw shell
    // actually executing `run` would have produced. A regression back to a raw, un-injected
    // `std::process::Command` shell-out (bypassing `self.deps.gates` entirely) would leave
    // "REAL_SHELL_WOULD_WRITE_THIS\n" here instead, and `runs` would be empty above - either
    // signal alone would fail this test, exactly the coverage no existing test (unit or
    // periphery) provides today.
    let final_c = std::fs::read_to_string(Path::new(&repo_path).join("c.rs")).unwrap();
    assert_eq!(
        final_c, "FAKE_REGEN_VIA_PORT\n",
        "the regenerated content must come from the injected gate::Runner port, never a raw \
         shell-out that bypassed it"
    );
    drop(repo);
}

/// A `gate::Runner` that runs every ordinary gate for real (delegating to `ExecRunner`) but
/// BLOCKS the `"regenerate"` gate id: it reports (over `entered_tx`) which worktree `dir` it
/// was called for, then waits on `release_rx` before actually running the command. Simulates
/// [`Self::build_budget`]'s real unbounded wait (spec 65) for a build slot every OTHER
/// concurrent gate - a sibling's own pre-merge "g" gate included - would otherwise contend for,
/// without needing to actually starve a real budget to prove the point: the test controls
/// exactly how long the call takes, and asserts on what can complete while it is still running.
struct BlockingRegenerateGateRunner {
    entered_tx: Mutex<std::sync::mpsc::Sender<String>>,
    release_rx: Mutex<std::sync::mpsc::Receiver<()>>,
}

impl rigger::gate::Runner for BlockingRegenerateGateRunner {
    fn run(
        &self,
        g: &rigger::gate::Gate,
        dir: &str,
        target_dir: &str,
        build_cache_dir: &str,
        build_cache_guard: &str,
        store_fence: &str,
        build_env: &rigger::gate::BuildEnv,
        budget: &rigger::budget::BuildBudget,
    ) -> rigger::gate::GateResult {
        if g.id == "regenerate" {
            self.entered_tx
                .lock()
                .unwrap()
                .send(dir.to_string())
                .expect("test thread must still be listening");
            self.release_rx
                .lock()
                .unwrap()
                .recv()
                .expect("test thread must release this call");
        }
        rigger::gate::ExecRunner.run(
            g,
            dir,
            target_dir,
            build_cache_dir,
            build_cache_guard,
            store_fence,
            build_env,
            budget,
        )
    }
}

/// Drives unit-a/unit-b through the same conflicting-`c.rs` shape as [`GatesPortConflictDriver`]
/// (whichever loses the integrate-lock race hits the confined-to-regenerable conflict), PLUS a
/// third, entirely independent unit-c (its own file, `d.rs`, never touched by a or b) whose
/// implementer commit is deliberately GATED: it waits on `proceed_rx` before writing anything,
/// so unit-c can only become ready to attempt its OWN merge once the test explicitly releases
/// it - never racing to integrate before the regenerate block below even begins. This is what
/// makes the ordering assertion meaningful: without the gate, unit-c (having no conflict of its
/// own) could race ahead and integrate before EITHER of unit-a/unit-b even reaches the
/// regenerate call, proving nothing about whether `integrate_mu` was held across it.
struct GatedThirdUnitDriver {
    repo: String,
    proceed_rx: Mutex<std::sync::mpsc::Receiver<()>>,
}

impl AgentDriver for GatedThirdUnitDriver {
    fn spawn(
        &self,
        _a: &AgentDef,
        _prompt: &str,
        opts: &SpawnOpts,
        _emit: &dyn Fn(&str, Value) -> Result<(), Error>,
    ) -> Result<AgentResult, Error> {
        let unit = opts.id.split('/').next().unwrap_or_default();
        if opts.id.contains("/implementer#") {
            if unit == "unit-c" {
                self.proceed_rx
                    .lock()
                    .unwrap()
                    .recv()
                    .expect("test thread must release unit-c");
                if !opts.dir.is_empty() {
                    std::fs::write(Path::new(&opts.dir).join("d.rs"), "C_LINE\n").unwrap();
                }
                return Ok(AgentResult::default());
            }
            if !opts.dir.is_empty() {
                // Barrier: both a/b branches must exist before either writes, so both cut
                // their worktree from the SAME base (mirrors GatesPortConflictDriver).
                for _ in 0..400 {
                    let n = Command::new("git")
                        .arg("-C")
                        .arg(&self.repo)
                        .args(["branch", "--list", "rigger/u/*"])
                        .output()
                        .map(|o| String::from_utf8_lossy(&o.stdout).lines().count())
                        .unwrap_or(0);
                    if n >= 2 {
                        break;
                    }
                    std::thread::sleep(std::time::Duration::from_millis(25));
                }
                let content = if unit == "unit-a" {
                    "A_LINE\n"
                } else {
                    "B_LINE\n"
                };
                std::fs::write(Path::new(&opts.dir).join("c.rs"), content).unwrap();
            }
            return Ok(AgentResult::default());
        }
        Ok(review_or_adjudicate(opts))
    }
}

#[test]
fn regenerate_never_holds_integrate_mu_letting_an_unrelated_unit_land_meanwhile() {
    let repo = init_repo();
    let repo_path = repo.path().to_str().unwrap().to_string();
    std::fs::write(Path::new(&repo_path).join("c.rs"), "BASE\n").unwrap();
    std::fs::write(Path::new(&repo_path).join("d.rs"), "BASE_D\n").unwrap();
    git_commit_all(&repo_path, "base c.rs + d.rs");

    let store = Store::open(":memory:").unwrap();
    let (proceed_tx, proceed_rx) = std::sync::mpsc::channel::<()>();
    let driver = GatedThirdUnitDriver {
        repo: repo_path.clone(),
        proceed_rx: Mutex::new(proceed_rx),
    };
    let (entered_tx, entered_rx) = std::sync::mpsc::channel::<String>();
    let (release_tx, release_rx) = std::sync::mpsc::channel::<()>();
    let runner = BlockingRegenerateGateRunner {
        entered_tx: Mutex::new(entered_tx),
        release_rx: Mutex::new(release_rx),
    };

    let mut cfg = Config::default();
    cfg.workflow.defaults.max_retries = 3;
    cfg.workflow.regenerate = vec![RegenerateRule {
        paths: vec!["c.rs".into()],
        run: "printf 'REGENERATED\\n' > c.rs".into(),
    }];
    cfg.agents.insert("worker".into(), agent("worker"));
    cfg.agents.insert("lens".into(), agent("lens"));
    cfg.agents.insert("judge".into(), agent("judge"));
    cfg.workflow.gates.insert("g".into(), gate_def("exit 0"));
    cfg.workflow
        .stages
        .insert("unit-a".into(), mk_stage("unit-a", "g"));
    cfg.workflow
        .stages
        .insert("unit-b".into(), mk_stage("unit-b", "g"));
    cfg.workflow
        .stages
        .insert("unit-c".into(), mk_stage("unit-c", "g"));

    let deps = Deps {
        store: &store,
        driver: &driver,
        gates: &runner,
        repo: repo_path.clone(),
        grounder: None,
        graph: None,
        criteria: Vec::new(),
    };

    // `run` blocks until the whole run reaches a terminal state, so it needs its own thread -
    // this test's own thread stays free to gate unit-c and poll the store while the regenerate
    // call below is deliberately stuck.
    let (unrelated_unit_integrated_while_blocked, rs) = std::thread::scope(|scope| {
        let run_handle = scope.spawn(|| run(&cfg, &deps));

        entered_rx
            .recv_timeout(std::time::Duration::from_secs(30))
            .expect(
                "the confined-to-regenerable conflict must reach the injected gate::Runner's \
                 \"regenerate\" id",
            );

        // ONLY NOW - once a real conflict is confirmed stuck inside the regenerate call - let
        // the entirely unrelated unit-c become ready to attempt its own merge. Releasing it any
        // earlier would let it race ahead and integrate before the block above even begins,
        // proving nothing about `integrate_mu`.
        proceed_tx.send(()).unwrap();

        // THE decisive proof (spec 88 criterion 1 round 2, adv-u88c1r1-budget-fix-worsens-
        // unfixed-lock-span): poll for unit-c's own, entirely unrelated merge to land while the
        // regenerate call above is STILL blocked. It can only complete this early if
        // `integrate_mu` was dropped around that call - held across it, unit-c's own
        // `wt.integrate` would itself be stuck waiting on the very same lock, since a or b is
        // still holding it inside the blocked regenerate call.
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(15);
        let mut landed = false;
        while std::time::Instant::now() < deadline {
            let events = store.read_stream(STREAM, 0, Direction::Forward).unwrap();
            if events.iter().any(|e| {
                e.type_ == ledger::TYPE_UNIT_INTEGRATED
                    && String::from_utf8_lossy(&e.data).contains("\"id\":\"unit-c\"")
            }) {
                landed = true;
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(20));
        }

        // Release the blocked call regardless of the outcome above, so `run` (and this test)
        // can always finish rather than hang the suite on a genuine regression.
        release_tx.send(()).unwrap();
        let rs = run_handle.join().unwrap().unwrap();
        (landed, rs)
    });

    assert!(
        unrelated_unit_integrated_while_blocked,
        "an entirely unrelated unit's own merge must land WHILE the conflicting unit's \
         regenerate-through-budget call is still blocked - integrate_mu must never be held \
         across it (spec 88 criterion 1 round 2, adv-u88c1r1-budget-fix-worsens-unfixed-lock-\
         span)"
    );

    assert_eq!(rs.units["unit-a"].status, ledger::Status::Integrated);
    assert_eq!(rs.units["unit-b"].status, ledger::Status::Integrated);
    assert_eq!(rs.units["unit-c"].status, ledger::Status::Integrated);
    let final_c = std::fs::read_to_string(Path::new(&repo_path).join("c.rs")).unwrap();
    assert_eq!(
        final_c, "REGENERATED\n",
        "the released regenerate call must still run for real and land its own output"
    );
    drop(repo);
}

// ============================================================================================
// Gap 6: a real crash between the source-resolving commit and the follow-up regenerate commit
// (adv-u88c1r1-crash-resume-permanently-skips-regeneration) has no PERMANENT test anywhere - the
// round-1 adversary's own proof was a temporary probe, reverted before it ever reached this file.
// ============================================================================================

/// Call 1's driver for the crash test: identical fixture shape to `MixedConflictDriver` (two
/// batch-mates conflicting on both `c.rs`, a source path, and `docs/audit/report.md`, a
/// registered regenerable path), but the ONE conflict-resolution re-park it ever answers
/// resolves the source conflict for real (a genuine, durable git commit) and then returns an
/// ordinary `Err` - simulating the process dying right there, after the commit lands on disk but
/// before `RunCtx::integrate_and_emit` ever reaches the follow-up regeneration.
struct CrashBeforeRegenerateDriver {
    repo: String,
    /// Which of unit-a/unit-b actually lost the integrate-lock race and hit the conflict -
    /// a genuine race between two concurrently-integrating siblings (mirrors every other
    /// fixture in this file), so the test reads this back afterward rather than assuming
    /// either name.
    loser: Mutex<Option<String>>,
}

impl AgentDriver for CrashBeforeRegenerateDriver {
    fn spawn(
        &self,
        _a: &AgentDef,
        _prompt: &str,
        opts: &SpawnOpts,
        _emit: &dyn Fn(&str, Value) -> Result<(), Error>,
    ) -> Result<AgentResult, Error> {
        let unit = opts.id.split('/').next().unwrap_or_default();
        if opts.id.contains("/implementer#") {
            if opts.id.contains("~retry") {
                assert!(
                    !opts.dir.is_empty(),
                    "a conflict re-park must still run in the unit's own worktree"
                );
                *self.loser.lock().unwrap() = Some(unit.to_string());
                std::fs::write(Path::new(&opts.dir).join("c.rs"), "RESOLVED_C\n").unwrap();
                // Only `c.rs`, deliberately NOT `-A`: this only succeeds because
                // `docs/audit/report.md` was already placeholder-staged by the conductor's own
                // `accept_incoming` before this spawn ran - the same load-bearing proof
                // `MixedConflictDriver`'s own `~retry2` arm relies on. This commit is the REAL,
                // durable crash boundary: everything up to and including it is genuinely on
                // disk when the `Err` below unwinds the whole `run()` call.
                git_commit_paths(&opts.dir, &["c.rs"], "resolve source conflict");
                return Err(Error(
                    "simulated crash: process dies right after the source commit, before \
                     regeneration ever runs"
                        .into(),
                ));
            }
            if !opts.dir.is_empty() {
                // Barrier: both branches must exist before either writes (mirrors
                // MixedConflictDriver), guaranteeing the same-line overlap on both files.
                for _ in 0..400 {
                    let n = Command::new("git")
                        .arg("-C")
                        .arg(&self.repo)
                        .args(["branch", "--list", "rigger/u/*"])
                        .output()
                        .map(|o| String::from_utf8_lossy(&o.stdout).lines().count())
                        .unwrap_or(0);
                    if n >= 2 {
                        break;
                    }
                    std::thread::sleep(std::time::Duration::from_millis(25));
                }
                let (c, audit) = if unit == "unit-a" {
                    ("A_C\n", "A_AUDIT\n")
                } else {
                    ("B_C\n", "B_AUDIT\n")
                };
                std::fs::write(Path::new(&opts.dir).join("c.rs"), c).unwrap();
                std::fs::create_dir_all(Path::new(&opts.dir).join("docs/audit")).unwrap();
                std::fs::write(Path::new(&opts.dir).join("docs/audit/report.md"), audit).unwrap();
            }
            return Ok(AgentResult::default());
        }
        Ok(review_or_adjudicate(opts))
    }
}

/// Call 2's driver: a FRESH `run()` against the same store+repo must NEVER reach the
/// conflict-resolution role again - proof that `integrate_and_emit`'s `Merged` arm answered the
/// still-owed regeneration from the durable log marker instead of re-entering conflict
/// resolution. Every OTHER role (an already-recorded stage the outer orchestration re-drives, or
/// simply never needs to) gets the same harmless, deterministic response call 1's driver would
/// have given it - safe to repeat idempotently either way.
struct NoConflictRespawnAfterCrashDriver;

impl AgentDriver for NoConflictRespawnAfterCrashDriver {
    fn spawn(
        &self,
        _a: &AgentDef,
        _prompt: &str,
        opts: &SpawnOpts,
        _emit: &dyn Fn(&str, Value) -> Result<(), Error>,
    ) -> Result<AgentResult, Error> {
        let unit = opts.id.split('/').next().unwrap_or_default();
        if opts.id.contains("/implementer#") {
            assert!(
                !opts.id.contains("~retry"),
                "the conflict-resolution role must NEVER be re-spawned on resume - the durable \
                 regenerate-pending ledger must answer the still-owed regeneration itself; got \
                 spawn id {:?}",
                opts.id
            );
            if !opts.dir.is_empty() {
                let (c, audit) = if unit == "unit-a" {
                    ("A_C\n", "A_AUDIT\n")
                } else {
                    ("B_C\n", "B_AUDIT\n")
                };
                std::fs::write(Path::new(&opts.dir).join("c.rs"), c).unwrap();
                std::fs::create_dir_all(Path::new(&opts.dir).join("docs/audit")).unwrap();
                std::fs::write(Path::new(&opts.dir).join("docs/audit/report.md"), audit).unwrap();
            }
            return Ok(AgentResult::default());
        }
        Ok(review_or_adjudicate(opts))
    }
}

#[test]
fn a_crash_between_the_source_commit_and_regeneration_still_regenerates_on_resume() {
    let repo = init_repo();
    let repo_path = repo.path().to_str().unwrap().to_string();
    std::fs::create_dir_all(Path::new(&repo_path).join("docs/audit")).unwrap();
    std::fs::write(Path::new(&repo_path).join("c.rs"), "BASE_C\n").unwrap();
    std::fs::write(
        Path::new(&repo_path).join("docs/audit/report.md"),
        "BASE_AUDIT\n",
    )
    .unwrap();
    git_commit_all(&repo_path, "base c.rs + docs/audit/report.md");

    let mut cfg = Config::default();
    cfg.workflow.defaults.max_retries = 3;
    cfg.workflow.regenerate = vec![RegenerateRule {
        paths: vec!["docs/audit/*".into()],
        run: "printf 'REGENERATED\\n' > docs/audit/report.md".into(),
    }];
    cfg.agents.insert("worker".into(), agent("worker"));
    cfg.agents.insert("lens".into(), agent("lens"));
    cfg.agents.insert("judge".into(), agent("judge"));
    cfg.workflow.gates.insert("g".into(), gate_def("exit 0"));
    cfg.workflow
        .stages
        .insert("unit-a".into(), mk_stage("unit-a", "g"));
    cfg.workflow
        .stages
        .insert("unit-b".into(), mk_stage("unit-b", "g"));

    let store = Store::open(":memory:").unwrap();

    // Call 1: a mixed conflict's source side resolves for real, then the process "crashes"
    // (an ordinary Err, not a park) before the follow-up regeneration ever runs. The repo on
    // disk keeps every commit made up to that point regardless of what this call returns.
    let loser = {
        let driver = CrashBeforeRegenerateDriver {
            repo: repo_path.clone(),
            loser: Mutex::new(None),
        };
        let deps = Deps {
            store: &store,
            driver: &driver,
            gates: &rigger::gate::ExecRunner,
            repo: repo_path.clone(),
            grounder: None,
            graph: None,
            criteria: Vec::new(),
        };
        let err = match run(&cfg, &deps) {
            Ok(_) => panic!(
                "call 1 must end in an Err - the simulated crash right after the source commit"
            ),
            Err(e) => e,
        };
        assert!(
            err.0.contains("simulated crash"),
            "call 1 must fail for the SIMULATED reason, not some other defect; got: {}",
            err.0
        );
        let loser = driver
            .loser
            .lock()
            .unwrap()
            .clone()
            .expect("the conflict-resolution role must have been spawned exactly once");
        loser
    };

    // A durable marker recording the still-owed regeneration must have survived call 1's crash -
    // the whole point of keying it off the log (conflict_regenerate_pending_from_log) rather
    // than an in-process accumulator local to the crashed call.
    let events_after_call_1 = store.read_stream(STREAM, 0, Direction::Forward).unwrap();
    assert!(
        events_after_call_1.iter().any(|e| {
            e.type_ == ledger::TYPE_UNIT_STATUS
                && String::from_utf8_lossy(&e.data)
                    .contains("integrate-conflict-regenerate-pending")
                && String::from_utf8_lossy(&e.data).contains("docs/audit/report.md")
        }),
        "call 1 must durably record the still-owed regeneration BEFORE the spawn that crashes, \
         not only accumulate it in memory"
    );
    assert!(
        !events_after_call_1.iter().any(|e| {
            e.type_ == ledger::TYPE_UNIT_INTEGRATED
                && String::from_utf8_lossy(&e.data).contains(&format!("\"id\":\"{loser}\""))
        }),
        "the losing unit ({loser}) must NOT be integrated yet - call 1 crashed before its merge \
         ever landed"
    );

    // Call 2: a genuinely fresh `run()` (a fresh RunCtx, fresh in-process state) against the
    // SAME store and repo - the real crash-resume shape, not a hand-seeded approximation.
    let driver2 = NoConflictRespawnAfterCrashDriver;
    let deps2 = Deps {
        store: &store,
        driver: &driver2,
        gates: &rigger::gate::ExecRunner,
        repo: repo_path.clone(),
        grounder: None,
        graph: None,
        criteria: Vec::new(),
    };
    let rs = run(&cfg, &deps2).expect("call 2 must resume and converge cleanly");

    assert_eq!(rs.units["unit-a"].status, ledger::Status::Integrated);
    assert_eq!(
        rs.units["unit-b"].status,
        ledger::Status::Integrated,
        "unit-b must still land on resume, never left dangling on the crashed merge"
    );
    assert_eq!(
        rs.units[loser.as_str()].attempts,
        0,
        "the crash-resumed regeneration is still infrastructure recovery, not a charged \
         remediation attempt (loser: {loser})"
    );

    let final_c = std::fs::read_to_string(Path::new(&repo_path).join("c.rs")).unwrap();
    assert_eq!(
        final_c, "RESOLVED_C\n",
        "the source path keeps call 1's real, pre-crash resolution - resume must never re-do \
         (or undo) it"
    );
    let final_audit =
        std::fs::read_to_string(Path::new(&repo_path).join("docs/audit/report.md")).unwrap();
    assert_eq!(
        final_audit, "REGENERATED\n",
        "the regenerable path must carry the REAL regenerated output on resume, not the \
         accept_incoming placeholder call 1's crash left frozen in place"
    );

    let log = git_out(&repo_path, &["log", "--format=%s"]);
    assert!(
        log.contains("regenerate conflicting artifacts for"),
        "the resumed call's own regeneration commit must land as a distinct commit; log:\n{log}"
    );
}

// ============================================================================================
// Gap 7 (round 2 review fix): the item-(e) fix's OWN cross-module seam - `Worktree::integrate`
// now surfaces a non-content merge failure as a genuine `Err`, and `integrate_and_emit` reads it
// through a bare `?` - has zero coverage anywhere in the diff. See the file header for the full
// rationale.
// ============================================================================================

/// `unit-b` lands `clash.rs` on the run branch for real, through the ordinary
/// implementer/gate/review/integrate pipeline; `unit-a` waits for that real landing (polling the
/// RUN BRANCH's own working tree, not just `unit-b`'s worktree existing) before writing its own
/// real work AND leaving a stray, untracked FIFO at the exact path `unit-b` just landed - the
/// only way `git add -A` (`Worktree::commit`'s own first step) can let a path survive untracked
/// all the way to `unit-a`'s later merge attempt.
struct NonContentMergeFailureDriver {
    repo: String,
}

impl AgentDriver for NonContentMergeFailureDriver {
    fn spawn(
        &self,
        _a: &AgentDef,
        _prompt: &str,
        opts: &SpawnOpts,
        _emit: &dyn Fn(&str, Value) -> Result<(), Error>,
    ) -> Result<AgentResult, Error> {
        let unit = opts.id.split('/').next().unwrap_or_default();
        if opts.id.contains("/implementer#") {
            if unit == "unit-b" {
                std::fs::write(Path::new(&opts.dir).join("clash.rs"), "B_LANDED\n").unwrap();
                return Ok(AgentResult::default());
            }
            // unit-a: its OWN worktree already branched off the ORIGINAL base (before
            // "clash.rs" existed anywhere) the instant this stage started - waiting here, before
            // writing anything, is what keeps that branch point pre-dating unit-b's landing.
            let clash = Path::new(&self.repo).join("clash.rs");
            let mut landed = false;
            for _ in 0..400 {
                if std::fs::read_to_string(&clash).ok().as_deref() == Some("B_LANDED\n") {
                    landed = true;
                    break;
                }
                std::thread::sleep(std::time::Duration::from_millis(25));
            }
            assert!(
                landed,
                "test setup: unit-b must land clash.rs on the run branch before unit-a proceeds"
            );
            std::fs::write(Path::new(&opts.dir).join("a.rs"), "A_WORK\n").unwrap();
            assert!(
                Command::new("mkfifo")
                    .arg(Path::new(&opts.dir).join("clash.rs"))
                    .status()
                    .unwrap()
                    .success(),
                "test setup: mkfifo must succeed"
            );
            return Ok(AgentResult::default());
        }
        Ok(review_or_adjudicate(opts))
    }
}

#[test]
#[cfg(unix)]
fn a_non_content_merge_failure_surfaces_as_a_run_error_leaving_branches_intact() {
    let repo = init_repo();
    let repo_path = repo.path().to_str().unwrap().to_string();

    let store = Store::open(":memory:").unwrap();
    let driver = NonContentMergeFailureDriver {
        repo: repo_path.clone(),
    };

    let mut cfg = Config::default();
    cfg.agents.insert("worker".into(), agent("worker"));
    cfg.agents.insert("lens".into(), agent("lens"));
    cfg.agents.insert("judge".into(), agent("judge"));
    cfg.workflow.gates.insert("g".into(), gate_def("exit 0"));
    cfg.workflow
        .stages
        .insert("unit-a".into(), mk_stage("unit-a", "g"));
    cfg.workflow
        .stages
        .insert("unit-b".into(), mk_stage("unit-b", "g"));

    let deps = Deps {
        store: &store,
        driver: &driver,
        gates: &rigger::gate::ExecRunner,
        repo: repo_path.clone(),
        grounder: None,
        graph: None,
        criteria: Vec::new(),
    };
    let err = match run(&cfg, &deps) {
        Err(e) => e,
        Ok(_) => panic!(
            "a non-content merge failure must surface as a genuine run() Err, never a silently \
             completed run"
        ),
    };
    assert!(
        err.0.contains("clash.rs") || err.0.to_lowercase().contains("untracked"),
        "the real git failure must propagate all the way out of run(), not be swallowed or \
         replaced by a fabricated message: {}",
        err.0
    );

    // unit-b's already-landed work is untouched by unit-a's LATER failure in the same wave -
    // the shared-state corruption the original finding warned a hard error could cause.
    let events = store.read_stream(STREAM, 0, Direction::Forward).unwrap();
    assert!(
        events.iter().any(|e| {
            e.type_ == ledger::TYPE_UNIT_INTEGRATED
                && String::from_utf8_lossy(&e.data).contains("\"id\":\"unit-b\"")
        }),
        "unit-b must have genuinely integrated before unit-a's failure was even reached"
    );
    assert!(
        !events.iter().any(|e| {
            e.type_ == ledger::TYPE_UNIT_INTEGRATED
                && String::from_utf8_lossy(&e.data).contains("\"id\":\"unit-a\"")
        }),
        "unit-a must never be recorded as integrated - its merge genuinely failed"
    );
    let landed = std::fs::read_to_string(Path::new(&repo_path).join("clash.rs")).unwrap();
    assert_eq!(
        landed, "B_LANDED\n",
        "the run branch's file content must be exactly unit-b's landed work, unperturbed by \
         unit-a's later, unrelated merge failure"
    );

    // unit-a's own durable branch keeps every prior commit (spec 88 criterion 1's own
    // guarantee, extended here to a non-content failure): its worktree DIRECTORY is reclaimed
    // (an ordinary terminal teardown, matching every other non-parked terminal exit), but the
    // branch itself is untouched - a single-parent commit carrying exactly unit-a's own real
    // work, never a partially-applied or corrupted merge.
    let branch_log = git_out(&repo_path, &["log", "--oneline", "rigger/u/unit-a"]);
    assert_eq!(
        branch_log.lines().count(),
        2,
        "unit-a's branch must carry exactly its base commit plus its own one real commit, no \
         partial merge state; got:\n{branch_log}"
    );
    let a_content = git_out(&repo_path, &["show", "rigger/u/unit-a:a.rs"]);
    assert_eq!(
        a_content, "A_WORK",
        "unit-a's own real work must survive on its branch untouched by the failed merge"
    );
    let clash_in_branch = Command::new("git")
        .arg("-C")
        .arg(&repo_path)
        .args(["cat-file", "-e", "rigger/u/unit-a:clash.rs"])
        .status()
        .unwrap()
        .success();
    assert!(
        !clash_in_branch,
        "unit-a's branch must never have actually merged clash.rs in - the merge was refused \
         before touching the tree, so the path stays absent from the branch's own history"
    );
    drop(repo);
}

// ============================================================================================
// Gap 8 (round 3 fix's own untested safety claim): a resumed `run()` must never double-record
// the durable regenerate-pending marker. See the file header for the full rationale.
// ============================================================================================

/// A single unit whose `implementer#` (non-retry) spawn fakes "a sibling already landed" by
/// mutating the BARE repo directly - the same technique `src/conductor.rs`'s own round-3 unit
/// test uses - then leaves its OWN worktree with a genuine, PERMANENT modify/delete conflict on
/// the regenerable path (`theirs` deletes it, `ours` modifies it) so `Worktree::accept_incoming`
/// can never succeed. Idempotent by construction: the run-branch mutation only fires once (it
/// checks the file is still there first), so if this driver were ever invoked a second time -
/// which a correct resume must NOT do, see `PanicOnAnyImplementerSpawnDriver` below - it would
/// still not corrupt the fixture.
struct PermanentModifyDeleteConflictDriver {
    repo: String,
}

impl AgentDriver for PermanentModifyDeleteConflictDriver {
    fn spawn(
        &self,
        _a: &AgentDef,
        _prompt: &str,
        opts: &SpawnOpts,
        _emit: &dyn Fn(&str, Value) -> Result<(), Error>,
    ) -> Result<AgentResult, Error> {
        if opts.id.contains("/implementer#") {
            assert!(
                !opts.id.contains("~retry"),
                "accept_incoming must fail and abort the whole call BEFORE any conflict- \
                 resolution re-park is ever spawned; got {}",
                opts.id
            );
            let gen_path = Path::new(&self.repo).join("gen.txt");
            if gen_path.exists() {
                std::fs::remove_file(&gen_path).unwrap();
                std::fs::write(Path::new(&self.repo).join("c.rs"), "OTHER_C\n").unwrap();
                git_commit_all(&self.repo, "other landed");
            }
            std::fs::write(Path::new(&opts.dir).join("c.rs"), "MINE_C\n").unwrap();
            std::fs::write(Path::new(&opts.dir).join("gen.txt"), "MINE_GEN\n").unwrap();
            return Ok(AgentResult::default());
        }
        Ok(review_or_adjudicate(opts))
    }
}

/// A resumed run's driver: the unit's implementer/review already recorded `Reviewed` before
/// the crash (call 1's failure unwinds from INSIDE `integrate_and_emit`, reached only after
/// that recording), so `ResumePhase::Reviewed` must skip straight to the integrate door -
/// the implementer must never be re-spawned at all on resume, retry suffix or not.
struct PanicOnAnyImplementerSpawnDriver;

impl AgentDriver for PanicOnAnyImplementerSpawnDriver {
    fn spawn(
        &self,
        _a: &AgentDef,
        _prompt: &str,
        opts: &SpawnOpts,
        _emit: &dyn Fn(&str, Value) -> Result<(), Error>,
    ) -> Result<AgentResult, Error> {
        assert!(
            !opts.id.contains("/implementer#"),
            "a resumed run, with the unit already Reviewed before the crash, must skip \
             straight to the integrate door (ResumePhase::Reviewed) - the implementer must \
             never be re-spawned on resume at all; got {}",
            opts.id
        );
        Ok(review_or_adjudicate(opts))
    }
}

fn count_regenerate_pending_markers(events: &[rigger::eventstore::Event]) -> usize {
    events
        .iter()
        .filter(|e| {
            e.type_ == ledger::TYPE_UNIT_STATUS
                && String::from_utf8_lossy(&e.data)
                    .contains("integrate-conflict-regenerate-pending")
                && String::from_utf8_lossy(&e.data).contains("gen.txt")
        })
        .count()
}

#[test]
fn a_resumed_run_after_accept_incoming_fails_never_double_records_the_regenerate_pending_marker() {
    let repo = init_repo();
    let repo_path = repo.path().to_str().unwrap().to_string();
    std::fs::write(Path::new(&repo_path).join("c.rs"), "BASE_C\n").unwrap();
    std::fs::write(Path::new(&repo_path).join("gen.txt"), "BASE_GEN\n").unwrap();
    git_commit_all(&repo_path, "base c.rs + gen.txt");

    let mut cfg = Config::default();
    cfg.workflow.defaults.max_retries = 3;
    cfg.workflow.regenerate = vec![RegenerateRule {
        paths: vec!["gen.txt".into()],
        run: "printf 'REGENERATED\\n' > gen.txt".into(),
    }];
    cfg.agents.insert("worker".into(), agent("worker"));
    cfg.agents.insert("lens".into(), agent("lens"));
    cfg.agents.insert("judge".into(), agent("judge"));
    cfg.workflow.gates.insert("g".into(), gate_def("exit 0"));
    cfg.workflow
        .stages
        .insert("unit-a".into(), mk_stage("unit-a", "g"));

    let store = Store::open(":memory:").unwrap();

    // Call 1: accept_incoming fails for real (a genuine, permanent modify/delete conflict -
    // `theirs` deleted the regenerable path outright, so there is no version to check out,
    // ever). The durable marker must already be on the log despite it, and exactly once.
    {
        let driver = PermanentModifyDeleteConflictDriver {
            repo: repo_path.clone(),
        };
        let deps = Deps {
            store: &store,
            driver: &driver,
            gates: &rigger::gate::ExecRunner,
            repo: repo_path.clone(),
            grounder: None,
            graph: None,
            criteria: Vec::new(),
        };
        let err = match run(&cfg, &deps) {
            Ok(_) => panic!(
                "call 1 must fail - accept_incoming's own checkout can never succeed against \
                 a deleted 'theirs' path"
            ),
            Err(e) => e,
        };
        assert!(
            err.0.contains("checkout") || err.0.contains("their version"),
            "call 1 must fail for the SIMULATED git reason (accept_incoming's own failing \
             checkout), not some other defect; got: {}",
            err.0
        );
    }
    let events_after_call_1 = store.read_stream(STREAM, 0, Direction::Forward).unwrap();
    assert_eq!(
        count_regenerate_pending_markers(&events_after_call_1),
        1,
        "call 1 must durably record the still-owed regeneration exactly once; events: \
         {events_after_call_1:?}"
    );

    // Call 2: a genuinely fresh `run()` (a fresh RunCtx, `replayed_keys` reseeded from the
    // STORE rather than carried over in memory) against the SAME store and repo - the real
    // crash-resume shape, not a hand-seeded approximation (mirrors GAP 6). Nothing between the
    // two calls touched the underlying git conflict, so accept_incoming fails again for the
    // IDENTICAL reason - proving it was genuinely retried, not skipped - and the point this
    // test exists for: the marker must still be recorded EXACTLY ONCE, never twice, because
    // `record_regenerate_pending`'s replay key (`unit-a/conflict-regen#0~1`) is the same both
    // times (neither `attempt` nor the per-episode `retry` counter survive a hard `run()` Err
    // to bump them) and the LOG - not the in-process map the round-3 fix's own comment credits
    // - is what a real restart actually reads back.
    {
        let driver2 = PanicOnAnyImplementerSpawnDriver;
        let deps2 = Deps {
            store: &store,
            driver: &driver2,
            gates: &rigger::gate::ExecRunner,
            repo: repo_path.clone(),
            grounder: None,
            graph: None,
            criteria: Vec::new(),
        };
        let err2 = match run(&cfg, &deps2) {
            Ok(_) => panic!(
                "call 2 must fail identically - nothing between the two calls resolved the \
                 underlying modify/delete conflict"
            ),
            Err(e) => e,
        };
        assert!(
            err2.0.contains("checkout") || err2.0.contains("their version"),
            "call 2 must fail for the SAME simulated git reason as call 1, proving \
             accept_incoming was genuinely retried on resume (not silently skipped); got: {}",
            err2.0
        );
    }
    let events_after_call_2 = store.read_stream(STREAM, 0, Direction::Forward).unwrap();
    assert_eq!(
        count_regenerate_pending_markers(&events_after_call_2),
        1,
        "a resumed run must NEVER double-record the durable regenerate-pending marker for the \
         same unit/attempt/retry - the log-keyed replay guard must dedup it even across a \
         genuine process restart, not just within one process; events: {events_after_call_2:?}"
    );

    drop(repo);
}
