//! Periphery (real-on-disk-config, real-git, cross-module) tests for spec 88, criterion 1
//! (INTEGRATE-CONFLICT MERGES): a unit whose integration hits a merge conflict is re-parked
//! with the run branch merged INTO its worktree instead of being reset off it, and a conflict
//! confined to a registered `regenerate:` path resolves itself with no spawn.
//!
//! WHAT THE IMPLEMENTER'S OWN TESTS ALREADY COVER (not re-proven here). `src/worktree.rs`'s
//! own `mod tests` proves `Worktree::integrate`'s merge-direction flip directly:
//! `conflicting_paths`/`merge_in_progress` read real worktree state, a conflict leaves markers
//! in place with the unit branch untouched, and a crash-resumed re-entry is idempotent.
//! `src/conductor.rs`'s own `mod tests` drives `run()` end to end with a fake `AgentDriver`
//! for three shapes: a plain re-park that resolves and both units land with no attempt
//! charged, a conflict CONFINED ENTIRELY to a registered regenerable path resolving with no
//! spawn at all, and the `CONFLICT_RESOLVE_BOUND`-exhausted fallback charging a real attempt
//! with cause `"integrate-conflict"`. None of that is re-derived here.
//!
//! WHAT THIS FILE OWNS - four gaps those inside-out layers are structurally blind to, found
//! by re-reading the diff against `git merge-base HEAD rigger-run` rather than by inspection
//! alone (recorded as `sdet-u88c1-boundary-accounting` and, for GAP 4, added on round 1's own
//! diff as `sdet-u88c1r1-boundary-accounting` / `sdet-u88c1r1-gap4-added-and-verified`).
//!
//! GAP 1, `regenerate_config_round_trips_through_the_real_on_disk_loader_with_back_compat`. The
//! implementer's own tests build `cfg.workflow.regenerate` via Rust struct literals; none of
//! them ever parse a real `regenerate:` YAML block through `config::load` (the actual
//! `serde(Deserialize)` surface a hand-authored `.rigger/workflow.yml` exercises). This drives
//! the real on-disk loader for a multi-rule, multi-path block, for the back-compat case (an
//! omitted key - every workflow.yml committed before this criterion existed - must resolve to
//! an empty list, not an error), and for the REAL, currently-committed project
//! `.rigger/workflow.yml` itself, pinning its own `docs/audit/*` rule.
//!
//! GAP 2,
//! `a_mixed_source_and_regenerable_conflict_resolves_the_source_first_then_regenerates_for_real`.
//! The Design's own CONSTRAINTS WALK names a conflict spanning BOTH a source file and a
//! registered regenerable path ("the artifact is regenerated by the conductor after the
//! implementer resolves the source conflict, in that order"), and the production code has a
//! whole branch dedicated to it (`Worktree::accept_incoming`, `resolve_integrate_conflict`'s
//! `regenerable`/`source` partition with `regenerable` non-empty AND `source` non-empty). Every
//! one of the implementer's three new conductor tests conflicts on exactly one file, entirely
//! source or entirely regenerable - the MIXED branch has zero coverage anywhere in the diff.
//! This drives it across TWO real retries (round 1 review, adv-u88c1-mixed-conflict-regen-
//! skipped-on-multiretry: a single-retry drive left the multi-retry accumulation bug - the
//! `regenerable` path staged on retry 1 losing itself out of `resolve_integrate_conflict`'s
//! per-iteration partition by the time retry 2 finally clears the tree - entirely uncaught) and
//! proves the re-park's `blast_radius` names only the source path on every retry, the
//! regenerable path is placeholder-resolved just enough to unblock the commit, and the FINAL
//! landed content is the real regenerated output (not the incoming placeholder silently
//! standing in for it forever, which is exactly what a retry-1-then-done drive cannot observe).
//!
//! GAP 3, `a_post_merge_red_rollback_resets_the_units_own_branch_not_just_the_repo`. This
//! diff's OWN new code comment states the failure mode precisely: "its NEXT attempt would
//! fast-forward the repo from a branch still carrying the abandoned merge commit, silently
//! erasing whatever the repo held." The pre-existing spec-12-unit-5 `MergeBreakDriver` test
//! (unmodified by this diff, only cross-referenced from a doc comment) asserts the REPO's tree
//! and the recorded cause, but never once inspects the LOSING unit's OWN branch ref - so it
//! cannot see whether `unit_head_before_merge`'s reset actually fires. This drives the identical
//! clean-merge-then-red-postmerge-gate scenario and inspects the loser's own worktree at its
//! retry spawn: the branch there must be a single-parent commit (the abandoned two-parent merge
//! commit discarded) carrying exactly the loser's own prior work (not over-corrected back to
//! the shared base either).
//!
//! GAP 4 (round 1 review fix), `regenerate_conflicted_paths_runs_through_the_injected_gates_
//! port_not_a_raw_shell_out`. Round 1 fixed `run_regenerate_command` to call the injected
//! `gate::Runner` port (`Deps.gates`) instead of a raw, un-injected `std::process::Command`
//! shell-out (arch-u88c1-regenerate-bypasses-runner-port-and-build-budget) - but every existing
//! test that exercises regeneration, this file's own GAP 2 included, wires `Deps.gates` to the
//! REAL `ExecRunner`, which runs the registered command as a real shell either way and so cannot
//! tell the two implementations apart. This drives the confined-to-regenerable scenario with a
//! fake `Runner` that intercepts only the `"regenerate"` gate id and proves BOTH that the port is
//! actually called (with the exact gate id/command/dir) and that the port's own output - not a
//! parallel raw shell-out's - is what lands.

use rigger::conductor::{run, AgentDriver, AgentResult, Deps, Error, SpawnOpts, STREAM};
use rigger::config::{self, AgentDef, Config, RegenerateRule, Stage};
use rigger::eventstore::sqlite::Store;
use rigger::eventstore::{Direction, EventStore};
use rigger::ledger;
use serde_json::Value;
use std::path::Path;
use std::process::Command;
use std::sync::Mutex;

/// A throwaway git repo with one empty commit, so a run-branch anchor (`HEAD`) resolves.
/// Mirrors `src/conductor.rs::tests::init_repo` (private to that module) and every other
/// periphery suite's identical copy (e.g. `tests/worktree_liveness_fence_periphery.rs`).
fn init_repo() -> tempfile::TempDir {
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path().to_str().unwrap();
    for args in [
        &["init", "-q"][..],
        &["config", "user.email", "t@example.com"],
        &["config", "user.name", "t"],
        &["commit", "--allow-empty", "-q", "-m", "init"],
    ] {
        Command::new("git")
            .arg("-C")
            .arg(p)
            .args(args)
            .output()
            .unwrap();
    }
    dir
}

fn git_out(dir: &str, args: &[&str]) -> String {
    let out = Command::new("git")
        .arg("-C")
        .arg(dir)
        .args(args)
        .output()
        .unwrap_or_else(|e| panic!("git {args:?} in {dir}: {e}"));
    String::from_utf8_lossy(&out.stdout).trim().to_string()
}

fn git_commit_all(dir: &str, msg: &str) {
    for args in [&["add", "-A"][..], &["commit", "-q", "-m", msg]] {
        Command::new("git")
            .arg("-C")
            .arg(dir)
            .args(args)
            .output()
            .unwrap();
    }
}

/// `git add <only these paths>` then commit - deliberately NOT `-A`, mirroring a real
/// implementer that stages exactly the paths it was told to resolve (its own `blast_radius`).
/// `git commit` refuses outright while ANY path remains unmerged, even one this call never
/// touched - so this only succeeds when every OTHER conflicting path (the regenerable one) was
/// already resolved by someone else first, making a caller of this fn a genuine, load-bearing
/// proof that resolution happened, not a blanket `-A` that would silently paper over it.
fn git_commit_paths(dir: &str, paths: &[&str], msg: &str) {
    let mut add = vec!["add", "--"];
    add.extend_from_slice(paths);
    for args in [add, vec!["commit", "-q", "-m", msg]] {
        let out = Command::new("git")
            .arg("-C")
            .arg(dir)
            .args(&args)
            .output()
            .unwrap_or_else(|e| panic!("git {args:?} in {dir}: {e}"));
        assert!(
            out.status.success(),
            "git {args:?} in {dir} failed (a leftover unresolved conflict would show up here): \
             {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }
}

fn agent(id: &str) -> AgentDef {
    AgentDef {
        id: id.to_string(),
        ..Default::default()
    }
}

fn gate_def(run: &str) -> config::Gate {
    config::Gate {
        run: run.to_string(),
        kind: "core".to_string(),
        inputs: Vec::new(),
    }
}

fn review_panel() -> config::ReviewPanel {
    config::ReviewPanel {
        lenses: vec!["lens".into()],
        adjudicator: "judge".into(),
        ..Default::default()
    }
}

/// The shared review-tier response every fake `AgentDriver` in this file returns for a
/// non-implementer spawn: the adjudicator approves outright, any other reviewer role's own
/// output is unread by the tests below (only its APPROVE verdict matters). One function, not a
/// third copy of the same two-armed match hand-duplicated across driver structs.
fn review_or_adjudicate(opts: &SpawnOpts) -> AgentResult {
    if opts.id.contains("/adjudicator#") {
        return AgentResult {
            output: r#"{"verdict":"approve"}"#.into(),
            resolved_model: String::new(),
        };
    }
    AgentResult {
        output: "reviewed the diff".into(),
        resolved_model: String::new(),
    }
}

fn mk_stage(name: &str, gate: &str) -> Stage {
    Stage {
        name: name.into(),
        agent: "worker".into(),
        gates: vec![gate.into()],
        on_pass: "merge".into(),
        needs: vec![],
        review: review_panel(),
        ..Default::default()
    }
}

// ============================================================================================
// Gap 1: the `regenerate:` YAML surface never round-trips through the real on-disk loader
// anywhere in the diff.
// ============================================================================================

/// Write a minimal but real `.rigger/agents/worker.md` + `.rigger/workflow.yml` at `root`, so
/// `config::load` reaches all the way through agent parsing and `Config::validate` - the real
/// on-disk boundary, not a struct literal built in memory. Mirrors
/// `tests/build_budget_slots_periphery.rs::write_workflow`'s identical technique for
/// `build.max_concurrent` (spec 65), now for `regenerate:` (spec 88, criterion 1).
/// `regenerate_block` is appended verbatim: `""` omits the section entirely (the back-compat
/// case).
fn write_workflow(root: &Path, regenerate_block: &str) {
    let rigger = root.join(".rigger");
    std::fs::create_dir_all(rigger.join("agents")).expect("create .rigger/agents");
    std::fs::write(
        rigger.join("agents").join("worker.md"),
        "---\nid: worker\nmodel: sonnet\ntools: [Read, Edit]\nisolation: none\n---\nDo the unit.\n",
    )
    .expect("write worker.md");
    let workflow = format!(
        "name: regeneratetest\n\
         defaults:\n  grounder: nop\n  budget: 60\n\
         stages:\n  a:\n    agent: worker\n    on_pass: none\n\
         {regenerate_block}"
    );
    std::fs::write(rigger.join("workflow.yml"), workflow).expect("write workflow.yml");
}

#[test]
fn regenerate_config_round_trips_through_the_real_on_disk_loader_with_back_compat() {
    // (a) a real regenerate: block, TWO rules, the first with TWO paths - proves the YAML
    // shape (a list of {paths: [...], run: ...} maps) round-trips field-for-field through
    // the real serde(Deserialize) surface, not just that SOME shape parses.
    let configured = tempfile::tempdir().expect("create temp project");
    write_workflow(
        configured.path(),
        "regenerate:\n\
         - paths: [\"docs/audit/*\", \"docs/other/*\"]\n\
         \u{20}\u{20}run: \"echo one\"\n\
         - paths: [\"gen/*.json\"]\n\
         \u{20}\u{20}run: \"echo two\"\n",
    );
    let cfg = config::load(configured.path().to_str().unwrap()).expect("load a valid workflow.yml");
    assert_eq!(
        cfg.workflow.regenerate.len(),
        2,
        "both rules must round-trip: {:?}",
        cfg.workflow.regenerate
    );
    assert_eq!(
        cfg.workflow.regenerate[0].paths,
        vec!["docs/audit/*".to_string(), "docs/other/*".to_string()]
    );
    assert_eq!(cfg.workflow.regenerate[0].run, "echo one");
    assert_eq!(
        cfg.workflow.regenerate[1].paths,
        vec!["gen/*.json".to_string()]
    );
    assert_eq!(cfg.workflow.regenerate[1].run, "echo two");

    // (b) the back-compat case: an OMITTED regenerate: key - every workflow.yml committed
    // before this criterion existed - must still load cleanly through the real loader and
    // resolve to an EMPTY list (every conflict re-parks the implementer exactly as it would
    // otherwise, per Workflow::regenerate's own doc comment), never an error and never a
    // silently-defaulted rule.
    let legacy = tempfile::tempdir().expect("create temp project");
    write_workflow(legacy.path(), "");
    let cfg = config::load(legacy.path().to_str().unwrap())
        .expect("a workflow.yml with no regenerate: section must still load");
    assert!(
        cfg.workflow.regenerate.is_empty(),
        "an omitted regenerate: section must resolve to an empty list through the real loader; \
         got {:?}",
        cfg.workflow.regenerate
    );

    // (c) the REAL, currently-committed project workflow.yml - not a synthetic fixture. It
    // must load through the exact same `config::load` path `main.rs` uses in production, and
    // its own registered rule (this diff's own worked example) must be exactly what the
    // committed file states: `docs/audit/*` regenerated via the simplification_audit test.
    let project_root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let real_cfg = config::load(project_root.to_str().unwrap())
        .expect("the project's own .rigger/workflow.yml must load through the real loader");
    assert!(
        real_cfg
            .workflow
            .regenerate
            .iter()
            .any(|r| r.paths == vec!["docs/audit/*".to_string()]
                && r.run.contains("simplification_audit")),
        "the real committed workflow.yml must register docs/audit/* as regenerable via the \
         simplification_audit regeneration command; got: {:?}",
        real_cfg.workflow.regenerate
    );
}

// ============================================================================================
// Gap 2: a conflict spanning BOTH a source path and a registered regenerable path (the
// Design's own CONSTRAINTS WALK scenario) has zero coverage anywhere in the diff.
// ============================================================================================

/// Drives the spec 88, criterion 1 MIXED-conflict fixture: `unit-a` and `unit-b` are two
/// batch-mates with no dependency, both editing the SAME LINE of BOTH `c.rs` (a plain source
/// file) and `docs/audit/report.md` (registered regenerable) off the same base - so the loser's
/// merge conflicts in both files at once. The barrier makes both worktrees branch from the same
/// base before either writes. The loser's own implementer is re-parked under a `~retry` id to
/// resolve ONLY the source conflict - across TWO real retries, not one: `~retry1` deliberately
/// leaves `c.rs` conflicted and commits nothing (forcing `resolve_integrate_conflict` around for
/// a SECOND pass, whose OWN `regenerable` partition of the by-then-shrunk `conflicting_paths()`
/// comes up empty - the exact shape `adv-u88c1-mixed-conflict-regen-skipped-on-multiretry`
/// found unaccumulated), then `~retry2` resolves it for real by overwriting `c.rs` with fixed
/// content and committing on the SAME branch. `docs/audit/report.md` is never touched by the
/// driver at any retry - left exactly as the conductor's own placeholder resolution (staged once,
/// on retry 1's iteration) left it - so the final content proves whether real regeneration ran
/// afterward, and specifically whether it still ran when the path that needed it was staged on
/// an EARLIER retry than the one that finally cleared the tree.
struct MixedConflictDriver {
    repo: String,
    calls: Mutex<Vec<String>>,
    /// `blast_radius` the conductor gave the retry spawn - captured so the test can assert it
    /// names only the source path, never the regenerable one.
    retry_blast_radius: Mutex<Option<Vec<String>>>,
}

impl AgentDriver for MixedConflictDriver {
    fn spawn(
        &self,
        _a: &AgentDef,
        _prompt: &str,
        opts: &SpawnOpts,
        _emit: &dyn Fn(&str, Value) -> Result<(), Error>,
    ) -> Result<AgentResult, Error> {
        self.calls.lock().unwrap().push(opts.id.clone());
        let unit = opts.id.split('/').next().unwrap_or_default();
        if opts.id.contains("/implementer#") {
            if opts.id.contains("~retry1") {
                assert!(
                    !opts.dir.is_empty(),
                    "a conflict re-park must still run in the unit's own worktree"
                );
                *self.retry_blast_radius.lock().unwrap() = Some(opts.blast_radius.clone());
                // Deliberately does NOT resolve the source conflict and commits nothing -
                // `c.rs` is left with its conflict markers exactly as `resolve_integrate_
                // conflict` found it. `docs/audit/report.md`, though, WAS already
                // placeholder-staged (via `accept_incoming`) before this spawn ran, so it no
                // longer shows up in `conflicting_paths()` either way. This forces the loop
                // around for a genuine SECOND retry, whose own `regenerable` partition of the
                // (by then audit-report-free) `conflicting` list comes up empty - the exact
                // shape that left the placeholder permanently on the run branch before the
                // fix: regeneration must still fire on retry 2's clean tree, from the
                // conductor's OWN accumulated bookkeeping, not from this iteration's local
                // partition.
                return Ok(AgentResult::default());
            }
            if opts.id.contains("~retry2") {
                assert!(
                    !opts.dir.is_empty(),
                    "a conflict re-park must still run in the unit's own worktree"
                );
                *self.retry_blast_radius.lock().unwrap() = Some(opts.blast_radius.clone());
                // NOW resolve the source conflict for real. `docs/audit/report.md` is still
                // left exactly as the conductor's own accept_incoming placeholder left it on
                // retry 1 - untouched here too - so the final landed content distinguishes
                // "the conductor really regenerated it afterward" from "the placeholder
                // silently stood in forever".
                std::fs::write(Path::new(&opts.dir).join("c.rs"), "RESOLVED_C\n").unwrap();
                // Stage and commit ONLY c.rs, the source path this spawn was told about - NOT
                // a blanket `-A`. `git commit` refuses outright while ANY path is still
                // unmerged, so this line only succeeds if `docs/audit/report.md` (which this
                // spawn never touches at all) was ALREADY resolved by the conductor's own
                // accept_incoming placeholder before this spawn ran - making this call itself
                // load-bearing proof that placeholder resolution happened, not merely a
                // downstream assertion that could pass by accident.
                git_commit_paths(&opts.dir, &["c.rs"], "resolve source conflict");
                return Ok(AgentResult::default());
            }
            if !opts.dir.is_empty() {
                for _ in 0..400 {
                    let n = Command::new("git")
                        .arg("-C")
                        .arg(&self.repo)
                        .args(["branch", "--list", "rigger/u/*"])
                        .output()
                        .map(|o| String::from_utf8_lossy(&o.stdout).lines().count())
                        .unwrap_or(0);
                    if n >= 2 {
                        break;
                    }
                    std::thread::sleep(std::time::Duration::from_millis(25));
                }
                let (c, audit) = if unit == "unit-a" {
                    ("A_C\n", "A_AUDIT\n")
                } else {
                    ("B_C\n", "B_AUDIT\n")
                };
                std::fs::write(Path::new(&opts.dir).join("c.rs"), c).unwrap();
                std::fs::create_dir_all(Path::new(&opts.dir).join("docs/audit")).unwrap();
                std::fs::write(Path::new(&opts.dir).join("docs/audit/report.md"), audit).unwrap();
            }
            return Ok(AgentResult::default());
        }
        Ok(review_or_adjudicate(opts))
    }
}

#[test]
fn a_mixed_source_and_regenerable_conflict_resolves_the_source_first_then_regenerates_for_real() {
    let repo = init_repo();
    let repo_path = repo.path().to_str().unwrap().to_string();
    std::fs::create_dir_all(Path::new(&repo_path).join("docs/audit")).unwrap();
    std::fs::write(Path::new(&repo_path).join("c.rs"), "BASE_C\n").unwrap();
    std::fs::write(
        Path::new(&repo_path).join("docs/audit/report.md"),
        "BASE_AUDIT\n",
    )
    .unwrap();
    git_commit_all(&repo_path, "base c.rs + docs/audit/report.md");

    let store = Store::open(":memory:").unwrap();
    let driver = MixedConflictDriver {
        repo: repo_path.clone(),
        calls: Mutex::new(Vec::new()),
        retry_blast_radius: Mutex::new(None),
    };

    let mut cfg = Config::default();
    cfg.workflow.defaults.max_retries = 3;
    cfg.workflow.regenerate = vec![RegenerateRule {
        paths: vec!["docs/audit/*".into()],
        run: "printf 'REGENERATED\\n' > docs/audit/report.md".into(),
    }];
    cfg.agents.insert("worker".into(), agent("worker"));
    cfg.agents.insert("lens".into(), agent("lens"));
    cfg.agents.insert("judge".into(), agent("judge"));
    cfg.workflow.gates.insert("g".into(), gate_def("exit 0"));
    cfg.workflow
        .stages
        .insert("unit-a".into(), mk_stage("unit-a", "g"));
    cfg.workflow
        .stages
        .insert("unit-b".into(), mk_stage("unit-b", "g"));

    let deps = Deps {
        store: &store,
        driver: &driver,
        gates: &rigger::gate::ExecRunner,
        repo: repo_path.clone(),
        grounder: None,
        graph: None,
        criteria: Vec::new(),
    };
    let rs = run(&cfg, &deps).unwrap();

    assert_eq!(rs.units["unit-a"].status, ledger::Status::Integrated);
    assert_eq!(
        rs.units["unit-b"].status,
        ledger::Status::Integrated,
        "the mixed conflict must still land, not dead-end"
    );
    assert_eq!(rs.units["unit-a"].attempts, 0);
    assert_eq!(
        rs.units["unit-b"].attempts, 0,
        "no remediation attempt is charged for a conflict, mixed or not"
    );

    // TWO real retry re-parks (round 1 review fix for adv-u88c1-mixed-conflict-regen-skipped-
    // on-multiretry): retry 1 deliberately leaves the source conflict unresolved, forcing
    // `resolve_integrate_conflict` around for a genuine second pass before it converges. Both
    // re-parks' blast_radius names ONLY the source path - the regenerable path the conductor
    // resolves itself must never reach the implementer, on either retry.
    let calls = driver.calls.lock().unwrap();
    assert!(
        calls.iter().any(|id| id.contains("/implementer#0~retry1")),
        "unit-b's implementer must be re-parked under a ~retry1 id; got {calls:?}"
    );
    assert!(
        calls.iter().any(|id| id.contains("/implementer#0~retry2")),
        "the mixed conflict must genuinely need a SECOND re-park (retry 1 deliberately leaves \
         it unresolved) to exercise the multi-retry regenerable-path bookkeeping; got {calls:?}"
    );
    let blast = driver.retry_blast_radius.lock().unwrap().clone();
    assert_eq!(
        blast,
        Some(vec!["c.rs".to_string()]),
        "the re-park's blast_radius must name only the source path, never the regenerable one \
         (checked against the LAST re-park, retry 2)"
    );

    // The FINAL landed content: c.rs carries the implementer's real resolution (from retry 2),
    // and docs/audit/report.md carries the conductor's REAL regenerated output - not the
    // accept_incoming placeholder (unit-a's "A_AUDIT\n") silently standing in forever. This is
    // the assertion the single-retry drive could never exercise: `docs/audit/report.md` was
    // placeholder-staged back on retry 1's iteration, two retries before the tree actually
    // clears on retry 2 - proving the conductor's accumulated bookkeeping (not retry 2's own,
    // by-then-empty `regenerable` partition) is what drives the real regeneration.
    let final_c = std::fs::read_to_string(Path::new(&repo_path).join("c.rs")).unwrap();
    assert_eq!(final_c, "RESOLVED_C\n");
    let final_audit =
        std::fs::read_to_string(Path::new(&repo_path).join("docs/audit/report.md")).unwrap();
    assert_eq!(
        final_audit, "REGENERATED\n",
        "the regenerable path must carry the conductor's OWN regenerated output, not the \
         placeholder incoming content the merge left it with"
    );

    // The conductor's own follow-up regeneration commit is a real, separately-attributable
    // commit (the design's "in that order"), not squashed into the implementer's resolution
    // commit. Read off the REPO's own current branch (not the unit's `rigger/u/*` ref, which
    // an integrated unit's branch/worktree may already have been reclaimed by the time this
    // assertion runs) - it carries the full landed history regardless.
    let log = git_out(&repo_path, &["log", "--format=%s"]);
    assert!(
        log.contains("regenerate conflicting artifacts for"),
        "the conductor's own regeneration commit must land as a distinct commit after the \
         implementer's resolution commit; log:\n{log}"
    );
    assert!(
        log.contains("resolve source conflict"),
        "the implementer's own resolution commit must land as its own distinct commit too; \
         log:\n{log}"
    );
    drop(repo);
}

// ============================================================================================
// Gap 3: the NEW `unit_head_before_merge` branch reset on a clean-merge-then-red-postmerge-gate
// - this diff's own doc comment names the exact failure mode a missing reset produces, and the
// pre-existing spec-12-unit-5 test never inspects the loser's own branch ref.
// ============================================================================================

const MB_BASE: &str = "unrelated line one\nunrelated line two\n";

/// Drives the identical clean-merge-then-red-postmerge-gate scenario the pre-existing
/// `MergeBreakDriver` (spec 12, unit 5) proves lands correctly on the REPO - `unit-a` prepends a
/// mark, `unit-b` appends one off the same base; both gate green alone, the merge auto-succeeds
/// (non-overlapping regions), but the merged tree carries two marks and the post-merge gate
/// rejects it. WHICH of the two loses the integrate-lock race (and so hits the post-merge-red
/// block) is a genuine race MergeBreakDriver itself never pins either - so, unlike that driver,
/// BOTH units here behave identically and symmetrically per attempt: attempt 0 reproduces the
/// break (prepend for a, append for b - so the loser's merge auto-succeeds without a raw
/// conflict), any later attempt - BEFORE writing anything - snapshots the worktree's CURRENT
/// branch state (the thing this test actually pins: a single-parent commit carrying the loser's
/// own prior work, or the abandoned two-parent merge commit the reset should have discarded)
/// and then writes NEUTRAL content (reverts its own side to unchanged base) so the retry's merge
/// carries only the winner's one mark and gates green.
struct BranchResetDriver {
    repo: String,
    /// One entry per unit whose implementer ran at `attempt > 0`: `(parent count, m.rs content)`
    /// of its worktree HEAD, captured before this driver wrote anything that attempt - i.e. the
    /// state the conductor's post-merge-red rollback left it in. Whichever of unit-a/unit-b
    /// loses the race gets exactly one entry here; the winner (never blocked, never retried)
    /// gets none.
    retry_snapshots: Mutex<std::collections::HashMap<String, (usize, String)>>,
}

impl AgentDriver for BranchResetDriver {
    fn spawn(
        &self,
        _a: &AgentDef,
        _prompt: &str,
        opts: &SpawnOpts,
        _emit: &dyn Fn(&str, Value) -> Result<(), Error>,
    ) -> Result<AgentResult, Error> {
        let unit = opts.id.split('/').next().unwrap_or_default().to_string();
        if opts.id.contains("/implementer#") {
            if !opts.dir.is_empty() {
                if opts.attempt == 0 {
                    for _ in 0..400 {
                        let n = Command::new("git")
                            .arg("-C")
                            .arg(&self.repo)
                            .args(["branch", "--list", "rigger/u/*"])
                            .output()
                            .map(|o| String::from_utf8_lossy(&o.stdout).lines().count())
                            .unwrap_or(0);
                        if n >= 2 {
                            break;
                        }
                        std::thread::sleep(std::time::Duration::from_millis(25));
                    }
                    // Reproduces the break: each unit adds its OWN mark in a DIFFERENT,
                    // non-overlapping region (prepend for a, append for b), same as
                    // MergeBreakDriver - whichever one integrates second merges cleanly into a
                    // tree that already carries the other's mark, producing two.
                    let content = if unit == "unit-a" {
                        format!("MARK\n{MB_BASE}")
                    } else {
                        format!("{MB_BASE}MARK\n")
                    };
                    std::fs::write(Path::new(&opts.dir).join("m.rs"), content).unwrap();
                } else {
                    // The retry: snapshot BEFORE writing anything - this is the state the
                    // conductor's post-merge-red rollback left the worktree in.
                    let head = git_out(&opts.dir, &["rev-parse", "HEAD"]);
                    let parents = git_out(&opts.dir, &["log", "-1", "--format=%P", &head]);
                    let parent_count = if parents.trim().is_empty() {
                        0
                    } else {
                        parents.split_whitespace().count()
                    };
                    let content =
                        std::fs::read_to_string(Path::new(&opts.dir).join("m.rs")).unwrap();
                    self.retry_snapshots
                        .lock()
                        .unwrap()
                        .insert(unit, (parent_count, content));
                    // The real fix: contribute NOTHING further to the shared region - this
                    // unit's own portion reverts to unchanged base, so the merged tree carries
                    // only the other unit's one mark and the post-merge gate goes green.
                    std::fs::write(Path::new(&opts.dir).join("m.rs"), MB_BASE).unwrap();
                }
            }
            return Ok(AgentResult::default());
        }
        Ok(review_or_adjudicate(opts))
    }
}

#[test]
fn a_post_merge_red_rollback_resets_the_units_own_branch_not_just_the_repo() {
    let repo = init_repo();
    let repo_path = repo.path().to_str().unwrap().to_string();
    std::fs::write(Path::new(&repo_path).join("m.rs"), MB_BASE).unwrap();
    git_commit_all(&repo_path, "base m.rs");

    let store = Store::open(":memory:").unwrap();
    let driver = BranchResetDriver {
        repo: repo_path.clone(),
        retry_snapshots: Mutex::new(std::collections::HashMap::new()),
    };

    let mut cfg = Config::default();
    // whichever unit loses the integrate-lock race must survive its FIRST block and get a
    // real second attempt: at least 2.
    cfg.workflow.defaults.max_retries = 2;
    cfg.agents.insert("worker".into(), agent("worker"));
    cfg.agents.insert("lens".into(), agent("lens"));
    cfg.agents.insert("judge".into(), agent("judge"));
    cfg.workflow.gates.insert(
        "g".into(),
        gate_def(
            "c=$(grep -c MARK m.rs 2>/dev/null); c=${c:-0}; \
             if [ \"$c\" -le 1 ]; then exit 0; else \
             echo 'gate g failed: merge introduced duplicate MARK'; exit 1; fi",
        ),
    );
    cfg.workflow
        .stages
        .insert("unit-a".into(), mk_stage("unit-a", "g"));
    cfg.workflow
        .stages
        .insert("unit-b".into(), mk_stage("unit-b", "g"));

    let deps = Deps {
        store: &store,
        driver: &driver,
        gates: &rigger::gate::ExecRunner,
        repo: repo_path.clone(),
        grounder: None,
        graph: None,
        criteria: Vec::new(),
    };
    let rs = run(&cfg, &deps).unwrap();

    // Both units integrate: the winner cleanly, the loser (whichever one lost the
    // integrate-lock race - a genuine race MergeBreakDriver itself never pins either) after
    // its rollback-and-retry recovers.
    assert_eq!(rs.units["unit-a"].status, ledger::Status::Integrated);
    assert_eq!(
        rs.units["unit-b"].status,
        ledger::Status::Integrated,
        "both units must land, or this test proves nothing about the retry state"
    );

    // Exactly one of the two took a retry (the loser); the winner never blocked.
    let snapshots = driver.retry_snapshots.lock().unwrap();
    assert_eq!(
        snapshots.len(),
        1,
        "exactly one unit (the loser of the integrate-lock race) must have retried; got {:?}",
        snapshots.keys().collect::<Vec<_>>()
    );
    let (loser, (parent_count, content)) = snapshots.iter().next().unwrap();
    let own_mark = if loser == "unit-a" {
        format!("MARK\n{MB_BASE}")
    } else {
        format!("{MB_BASE}MARK\n")
    };

    // The actual claim: at the retry, the loser's worktree HEAD was a SINGLE-parent commit
    // (the abandoned two-parent auto-merge commit was discarded by the branch reset, not just
    // the repo) carrying EXACTLY the loser's own prior work - not the base content either
    // (which would mean the reset over-corrected and threw away its real, reviewed work too).
    assert_eq!(
        *parent_count, 1,
        "{loser}'s own branch must be reset to its single-parent pre-merge commit, not left \
         carrying the abandoned two-parent merge commit the post-merge-red rollback discarded \
         on the repo side"
    );
    assert_eq!(
        *content, own_mark,
        "the reset must land on EXACTLY {loser}'s own prior work (its one-mark commit), \
         neither the abandoned merge commit's two-mark content nor an over-corrected reset all \
         the way back to the shared base"
    );

    // The merged tree carries exactly one mark (the winner's); the broken two-mark tree from
    // the loser's first attempt never landed.
    let merged = std::fs::read_to_string(Path::new(&repo_path).join("m.rs")).unwrap();
    assert_eq!(
        merged.matches("MARK").count(),
        1,
        "the run branch holds only the winner's one mark: {merged}"
    );

    // The block that triggered the rollback is stamped "integrate-conflict" (spec 69's cause
    // wire), same as the pre-existing MergeBreakDriver test - reused here as a sanity check,
    // not re-derived.
    let events = store.read_stream(STREAM, 0, Direction::Forward).unwrap();
    let cause = events
        .iter()
        .find(|e| {
            e.type_ == ledger::TYPE_UNIT_FAILED
                && String::from_utf8_lossy(&e.data).contains(&format!("\"id\":\"{loser}\""))
        })
        .map(|e| serde_json::from_slice::<Value>(&e.data).unwrap()["cause"].clone());
    assert_eq!(cause, Some(Value::String("integrate-conflict".into())));
    drop(repo);
}

// ============================================================================================
// Gap 4: `run_regenerate_command`'s NEW cross-module call into the injected `gate::Runner`
// port (round 1 review fix for arch-u88c1-regenerate-bypasses-runner-port-and-build-budget) has
// zero test anywhere that can tell a real port-routed call apart from a raw, un-injected
// `std::process::Command` shell-out producing the same visible result: every existing test that
// exercises regeneration - the implementer's own three conductor.rs unit tests AND this file's
// GAP 2 - wires `Deps.gates` to the REAL `rigger::gate::ExecRunner`, which actually runs the
// registered shell command either way. Reverting `run_regenerate_command` back to a raw
// `std::process::Command::new("sh")` call (the exact regression the fix's own doc comment names)
// would still make every one of those tests pass unchanged, because they only ever check the
// resulting file content, never which side of the port boundary produced it.
// ============================================================================================

/// A [`rigger::gate::Runner`] fake that ONLY intercepts the `"regenerate"` gate id (recording
/// its call - gate id, gate run command, dir - and writing its OWN sentinel content instead of
/// actually running `g.run` as a shell command); every OTHER gate id (a unit's ordinary `"g"`
/// gate, the post-merge re-gate) delegates straight to the REAL [`rigger::gate::ExecRunner`], so
/// this fake changes nothing about how the surrounding conflict/merge/gate machinery behaves -
/// it observes exactly one seam. The regenerate rule's `run` string below is deliberately a
/// command that would write DIFFERENT content if a raw shell ever executed it for real, so the
/// two paths can never coincidentally agree on the final file content: only one of them can have
/// produced it.
struct RecordingGateRunner {
    calls: Mutex<Vec<(String, String, String)>>,
}

impl rigger::gate::Runner for RecordingGateRunner {
    fn run(
        &self,
        g: &rigger::gate::Gate,
        dir: &str,
        target_dir: &str,
        build_cache_dir: &str,
        build_cache_guard: &str,
        store_fence: &str,
        build_env: &rigger::gate::BuildEnv,
        budget: &rigger::budget::BuildBudget,
    ) -> rigger::gate::GateResult {
        if g.id != "regenerate" {
            return rigger::gate::ExecRunner.run(
                g,
                dir,
                target_dir,
                build_cache_dir,
                build_cache_guard,
                store_fence,
                build_env,
                budget,
            );
        }
        self.calls
            .lock()
            .unwrap()
            .push((g.id.clone(), g.run.clone(), dir.to_string()));
        std::fs::write(Path::new(dir).join("c.rs"), "FAKE_REGEN_VIA_PORT\n").unwrap();
        rigger::gate::GateResult {
            pass: true,
            evidence: "fake runner: regenerated via the injected port, never a raw shell".into(),
        }
    }
}

/// Same two-batch-mates-same-line-off-the-same-base shape as the implementer's own
/// `conflict_fixture` (conductor.rs) and this file's other drivers: `c.rs` is registered
/// regenerable, so the loser's conflict resolves with NO implementer spawn at all - this test's
/// whole point is the conductor's OWN regeneration call, not anything an implementer does.
struct GatesPortConflictDriver {
    repo: String,
    calls: Mutex<Vec<String>>,
}

impl AgentDriver for GatesPortConflictDriver {
    fn spawn(
        &self,
        _a: &AgentDef,
        _prompt: &str,
        opts: &SpawnOpts,
        _emit: &dyn Fn(&str, Value) -> Result<(), Error>,
    ) -> Result<AgentResult, Error> {
        self.calls.lock().unwrap().push(opts.id.clone());
        let unit = opts.id.split('/').next().unwrap_or_default();
        if opts.id.contains("/implementer#") {
            if !opts.dir.is_empty() {
                // Barrier: wait until BOTH units' worktrees exist before either writes, so both
                // branch off the identical base commit (mirrors MixedConflictDriver above).
                for _ in 0..400 {
                    let n = Command::new("git")
                        .arg("-C")
                        .arg(&self.repo)
                        .args(["branch", "--list", "rigger/u/*"])
                        .output()
                        .map(|o| String::from_utf8_lossy(&o.stdout).lines().count())
                        .unwrap_or(0);
                    if n >= 2 {
                        break;
                    }
                    std::thread::sleep(std::time::Duration::from_millis(25));
                }
                let content = if unit == "unit-a" {
                    "A_LINE\n"
                } else {
                    "B_LINE\n"
                };
                std::fs::write(Path::new(&opts.dir).join("c.rs"), content).unwrap();
            }
            return Ok(AgentResult::default());
        }
        Ok(review_or_adjudicate(opts))
    }
}

#[test]
fn regenerate_conflicted_paths_runs_through_the_injected_gates_port_not_a_raw_shell_out() {
    let repo = init_repo();
    let repo_path = repo.path().to_str().unwrap().to_string();
    std::fs::write(Path::new(&repo_path).join("c.rs"), "BASE\n").unwrap();
    git_commit_all(&repo_path, "base c.rs");

    let store = Store::open(":memory:").unwrap();
    let driver = GatesPortConflictDriver {
        repo: repo_path.clone(),
        calls: Mutex::new(Vec::new()),
    };
    let runner = RecordingGateRunner {
        calls: Mutex::new(Vec::new()),
    };

    let mut cfg = Config::default();
    cfg.workflow.defaults.max_retries = 3;
    cfg.workflow.regenerate = vec![RegenerateRule {
        paths: vec!["c.rs".into()],
        run: "printf 'REAL_SHELL_WOULD_WRITE_THIS\\n' > c.rs".into(),
    }];
    cfg.agents.insert("worker".into(), agent("worker"));
    cfg.agents.insert("lens".into(), agent("lens"));
    cfg.agents.insert("judge".into(), agent("judge"));
    cfg.workflow.gates.insert("g".into(), gate_def("exit 0"));
    cfg.workflow
        .stages
        .insert("unit-a".into(), mk_stage("unit-a", "g"));
    cfg.workflow
        .stages
        .insert("unit-b".into(), mk_stage("unit-b", "g"));

    let deps = Deps {
        store: &store,
        driver: &driver,
        gates: &runner,
        repo: repo_path.clone(),
        grounder: None,
        graph: None,
        criteria: Vec::new(),
    };
    let rs = run(&cfg, &deps).unwrap();

    assert_eq!(rs.units["unit-a"].status, ledger::Status::Integrated);
    assert_eq!(
        rs.units["unit-b"].status,
        ledger::Status::Integrated,
        "a conflict confined entirely to a registered regenerable path must still land"
    );
    assert_eq!(rs.units["unit-a"].attempts, 0);
    assert_eq!(rs.units["unit-b"].attempts, 0);

    let calls = driver.calls.lock().unwrap();
    assert!(
        !calls.iter().any(|id| id.contains("~retry")),
        "a conflict confined to a registered regenerable path resolves with NO spawn; got {calls:?}"
    );

    // THE decisive proof of DI routing: the injected port was actually invoked, carrying the
    // EXACT gate id and command `run_regenerate_command` documents constructing, in the unit's
    // own worktree dir - never the shared repo dir.
    let runs = runner.calls.lock().unwrap();
    assert_eq!(
        runs.len(),
        1,
        "regenerate_conflicted_paths must call the injected gate::Runner port exactly once for \
         the one distinct registered command; got {runs:?}"
    );
    let (id, run_cmd, dir) = &runs[0];
    assert_eq!(
        id, "regenerate",
        "run_regenerate_command's own Gate literal must carry id \"regenerate\""
    );
    assert_eq!(
        run_cmd, "printf 'REAL_SHELL_WOULD_WRITE_THIS\\n' > c.rs",
        "the injected port must receive the EXACT command the registered RegenerateRule names"
    );
    assert_ne!(
        dir, &repo_path,
        "the port must be called with the LOSING unit's own worktree dir, never the shared repo \
         (the worktree itself may already be reclaimed by the time this assertion runs, since \
         both units have finished integrating - matching GAP 2/3's own convention of reading \
         final state off the repo, never a per-unit worktree, after `run()` returns)"
    );
    assert!(
        dir.contains("unit-a") || dir.contains("unit-b"),
        "the regenerable-confined conflict belongs to whichever unit loses the integrate-lock \
         race (a genuine race, never pinned - see GAP 3's identical caveat); got {dir}"
    );

    // The final landed content is the FAKE runner's own sentinel - never the string a raw shell
    // actually executing `run` would have produced. A regression back to a raw, un-injected
    // `std::process::Command` shell-out (bypassing `self.deps.gates` entirely) would leave
    // "REAL_SHELL_WOULD_WRITE_THIS\n" here instead, and `runs` would be empty above - either
    // signal alone would fail this test, exactly the coverage no existing test (unit or
    // periphery) provides today.
    let final_c = std::fs::read_to_string(Path::new(&repo_path).join("c.rs")).unwrap();
    assert_eq!(
        final_c, "FAKE_REGEN_VIA_PORT\n",
        "the regenerated content must come from the injected gate::Runner port, never a raw \
         shell-out that bypassed it"
    );
    drop(repo);
}
